package frontend.principal;

import java.awt.Color;
import java.awt.Dimension;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author michael
 */
public class LoginPanel extends javax.swing.JPanel {

    private boolean validLogin = false;

    /**
     * Creates new form LoginPanel
     */
    public LoginPanel() {
        initComponents();
        this.defaulTxt();
        validLogin = false;
    }

    public boolean isValidLogin() {
        return validLogin;
    }

    public String getRol() {
        if (rolUserCombobox.getSelectedIndex() == 0) {
            return "Administrador";
        }
        if (rolUserCombobox.getSelectedIndex() == 1) {
            return "Inventario";
        }
        if (rolUserCombobox.getSelectedIndex() == 2) {
            return "Entrenador";
        }
        if (rolUserCombobox.getSelectedIndex() == 3) {
            return "Recepcionista";
        }
        return "";
    }

    public void setValidLogin(boolean validLogin) {
        boolean old = this.validLogin;
        this.validLogin = validLogin;
        firePropertyChange("validLogin", old, validLogin);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        userIdTextField = new javax.swing.JTextField();
        passwordField = new javax.swing.JPasswordField();
        loginBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        rolUserCombobox = new javax.swing.JComboBox<>();

        setOpaque(false);
        setLayout(new java.awt.GridBagLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Hack NFM", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Inicio de Sesión");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 200, 0, 234);
        add(jLabel1, gridBagConstraints);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Hack NFM", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Usuario:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 39;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(49, 171, 0, 0);
        add(jLabel2, gridBagConstraints);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Hack NFM", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Contraseña:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 37;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(38, 139, 0, 0);
        add(jLabel3, gridBagConstraints);

        userIdTextField.setMaximumSize(new java.awt.Dimension(200, 2147483647));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 200;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(41, 19, 0, 0);
        add(userIdTextField, gridBagConstraints);

        passwordField.setMaximumSize(new java.awt.Dimension(200, 2147483647));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 200;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(38, 19, 0, 0);
        add(passwordField, gridBagConstraints);

        loginBtn.setFont(new java.awt.Font("Hack Nerd Font Mono", 0, 24)); // NOI18N
        loginBtn.setForeground(new java.awt.Color(0, 255, 51));
        loginBtn.setText("Ingresar");
        loginBtn.setBorder(null);
        loginBtn.setOpaque(true);
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(61, 350, 122, 0);
        add(loginBtn, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Hack NFM", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Tipo de empleado:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(39, 78, 0, 0);
        add(jLabel4, gridBagConstraints);

        rolUserCombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Administrador Inventario", "Entrenador", "Recepcionista" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipadx = 24;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(34, 20, 0, 0);
        add(rolUserCombobox, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        if (userIdTextField.getText().isEmpty() || passwordField.getText().isBlank() || (userIdTextField.getText().isEmpty() && passwordField.getText().isBlank())) {
            JOptionPane.showMessageDialog(this, "Hay campos vacíos, llenelos por favor", "Campos necesarios", JOptionPane.INFORMATION_MESSAGE);
            loginBtn.setForeground(Color.red);
            setValidLogin(false);
        } else {
            setValidLogin(true);
            validLogin = true;
            System.out.println("Ingresado");
            userIdTextField.setText("");
            passwordField.setText("");
            rolUserCombobox.setSelectedIndex(0);
        }
    }//GEN-LAST:event_loginBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton loginBtn;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JComboBox<String> rolUserCombobox;
    private javax.swing.JTextField userIdTextField;
    // End of variables declaration//GEN-END:variables

    private void defaulTxt() {
        userIdTextField.setPreferredSize(new Dimension(60, 20));
        userIdTextField.setMinimumSize(new Dimension(60, 20));
        userIdTextField.setMaximumSize(new Dimension(60, 20));
        passwordField.setPreferredSize(new Dimension(60, 20));
        passwordField.setMinimumSize(new Dimension(60, 20));
        passwordField.setMaximumSize(new Dimension(60, 20));
    }
}
