package frontend.principal;

import backend.util.ColorApp;
import com.formdev.flatlaf.FlatClientProperties;
import frontend.admin.GeneratedReportPanel;
import frontend.admin.NewEmployeePanel;
import frontend.inventorymanager.SendEquipmentPanel;
import frontend.inventorymanager.RegisterEquipmentPanel;
import frontend.inventorymanager.ReportEquipmentPanel;
import frontend.receptionist.AssistanceClientPanel;
import frontend.receptionist.ClientHistoryPanel;
import frontend.receptionist.ClientListPanel;
import frontend.receptionist.NewClientPanel;
import frontend.trainer.AssingClientPanel;
import frontend.trainer.RoutineAttendancePanel;
import java.awt.BorderLayout;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author michael
 */
public class MainWindow extends javax.swing.JFrame {

    public static final String TITTLE = "Fit - Manager";
    private final PanelBackground panelBackground = new PanelBackground();
    private final LoginPanel loginPanel = new LoginPanel();
    private final GeneratedReportPanel generatedReportPanel = new GeneratedReportPanel();
    private final SendEquipmentPanel sendEquipmentPanel = new SendEquipmentPanel();
    private final NewClientPanel receptionistPanel = new NewClientPanel();
    private final AssingClientPanel assingClientPanel = new AssingClientPanel();
    private final NewClientPanel clientPanel = new NewClientPanel();
    private final ClientListPanel clientListPanel = new ClientListPanel();
    private final ClientHistoryPanel historyPanel = new ClientHistoryPanel();
    private final RegisterEquipmentPanel registerEquipmentPanel = new RegisterEquipmentPanel();
    private final ReportEquipmentPanel equipmentPanel = new ReportEquipmentPanel();
    private final RoutineAttendancePanel attendancePanel = new RoutineAttendancePanel();
    private final NewEmployeePanel employeePanel = new NewEmployeePanel();
    private final AssistanceClientPanel assistanceClientPanel = new AssistanceClientPanel();

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        this.setContentPane(panelBackground);
        initComponents();
        this.styleMenuBarFlatLaf();
        this.paintPanel(loginPanel);
        this.setIconImage(getIconImage());
        this.setTitle(TITTLE);
        this.menuBar.setVisible(false);
        this.viewMenuBar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        menuBar = new javax.swing.JPanel();
        logoutBtn = new javax.swing.JButton();
        newClientBtn = new javax.swing.JButton();
        viewClientsBtn = new javax.swing.JButton();
        clientsHistoryBtn = new javax.swing.JButton();
        membershipsBtn = new javax.swing.JButton();
        registerEquipmentBtn = new javax.swing.JButton();
        requestEquipmentBtn = new javax.swing.JButton();
        sendEquipmentBtn = new javax.swing.JButton();
        reportEquipmentBtn = new javax.swing.JButton();
        assingClientBtn = new javax.swing.JButton();
        routinesBtn = new javax.swing.JButton();
        reportsBtn = new javax.swing.JButton();
        newEmployeeBtn = new javax.swing.JButton();
        assistanceClientBtn = new javax.swing.JButton();
        newRoutine = new javax.swing.JButton();
        contentPane = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 650));

        menuBar.setLayout(new java.awt.GridBagLayout());

        logoutBtn.setText("Cerrar Sesión");
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 14;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 8, 20, 8);
        menuBar.add(logoutBtn, gridBagConstraints);

        newClientBtn.setText("Registrar Cliente");
        newClientBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newClientBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 8, 20, 8);
        menuBar.add(newClientBtn, gridBagConstraints);

        viewClientsBtn.setText("Ver Clientes");
        viewClientsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewClientsBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 8, 20, 8);
        menuBar.add(viewClientsBtn, gridBagConstraints);

        clientsHistoryBtn.setText("Historial de Clientes");
        clientsHistoryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientsHistoryBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 8, 20, 8);
        menuBar.add(clientsHistoryBtn, gridBagConstraints);

        membershipsBtn.setText("Membresías y pagos");
        membershipsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                membershipsBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 8, 20, 8);
        menuBar.add(membershipsBtn, gridBagConstraints);

        registerEquipmentBtn.setText("Registrar Equipo");
        registerEquipmentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerEquipmentBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 8, 20, 8);
        menuBar.add(registerEquipmentBtn, gridBagConstraints);

        requestEquipmentBtn.setText("Solicitar Equipo");
        requestEquipmentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestEquipmentBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 8, 20, 8);
        menuBar.add(requestEquipmentBtn, gridBagConstraints);

        sendEquipmentBtn.setText("Envíar Equipo");
        sendEquipmentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendEquipmentBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 8, 20, 8);
        menuBar.add(sendEquipmentBtn, gridBagConstraints);

        reportEquipmentBtn.setText("Reportar Equipo");
        reportEquipmentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportEquipmentBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 8, 20, 8);
        menuBar.add(reportEquipmentBtn, gridBagConstraints);

        assingClientBtn.setText("Asignar Cliente");
        assingClientBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assingClientBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 8, 20, 8);
        menuBar.add(assingClientBtn, gridBagConstraints);

        routinesBtn.setText("Rutinas");
        routinesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                routinesBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 8, 20, 8);
        menuBar.add(routinesBtn, gridBagConstraints);

        reportsBtn.setText("Reportes");
        reportsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportsBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 8, 20, 8);
        menuBar.add(reportsBtn, gridBagConstraints);

        newEmployeeBtn.setText("Nuevo Empleado");
        newEmployeeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newEmployeeBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 13;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 8, 20, 8);
        menuBar.add(newEmployeeBtn, gridBagConstraints);

        assistanceClientBtn.setText("Asistencias");
        assistanceClientBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assistanceClientBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 8, 20, 8);
        menuBar.add(assistanceClientBtn, gridBagConstraints);

        newRoutine.setText("Crear Rutina");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 8, 20, 8);
        menuBar.add(newRoutine, gridBagConstraints);

        contentPane.setMinimumSize(new java.awt.Dimension(600, 800));
        contentPane.setOpaque(false);
        contentPane.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(contentPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(menuBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contentPane, javax.swing.GroupLayout.PREFERRED_SIZE, 365, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        int logout = JOptionPane.showConfirmDialog(this, "¿Seguro que desea cerrar sesión?", "¿Cerrar Sesión?", JOptionPane.YES_NO_OPTION);
        if (logout == 0) {
            this.setSize(800, 650);
            this.menuBar.setVisible(false);
            loginPanel.setValidLogin(false);
            paintPanel(loginPanel);
        }
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void newClientBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newClientBtnActionPerformed
       paintPanel(clientPanel);
    }//GEN-LAST:event_newClientBtnActionPerformed

    private void viewClientsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewClientsBtnActionPerformed
        paintPanel(clientListPanel);
    }//GEN-LAST:event_viewClientsBtnActionPerformed

    private void clientsHistoryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientsHistoryBtnActionPerformed
        paintPanel(historyPanel);
    }//GEN-LAST:event_clientsHistoryBtnActionPerformed

    private void membershipsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_membershipsBtnActionPerformed
        paintPanel(historyPanel);
    }//GEN-LAST:event_membershipsBtnActionPerformed

    private void registerEquipmentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerEquipmentBtnActionPerformed
       paintPanel(registerEquipmentPanel);
    }//GEN-LAST:event_registerEquipmentBtnActionPerformed

    private void requestEquipmentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestEquipmentBtnActionPerformed
        paintPanel(equipmentPanel);
    }//GEN-LAST:event_requestEquipmentBtnActionPerformed

    private void sendEquipmentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendEquipmentBtnActionPerformed
        paintPanel(sendEquipmentPanel);
    }//GEN-LAST:event_sendEquipmentBtnActionPerformed

    private void reportEquipmentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportEquipmentBtnActionPerformed
        paintPanel(equipmentPanel);
    }//GEN-LAST:event_reportEquipmentBtnActionPerformed

    private void assingClientBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assingClientBtnActionPerformed
        paintPanel(assingClientPanel);
    }//GEN-LAST:event_assingClientBtnActionPerformed

    private void routinesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_routinesBtnActionPerformed
        paintPanel(attendancePanel);
    }//GEN-LAST:event_routinesBtnActionPerformed

    private void reportsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportsBtnActionPerformed
        paintPanel(generatedReportPanel);
    }//GEN-LAST:event_reportsBtnActionPerformed

    private void newEmployeeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newEmployeeBtnActionPerformed
        paintPanel(employeePanel);
    }//GEN-LAST:event_newEmployeeBtnActionPerformed

    private void assistanceClientBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assistanceClientBtnActionPerformed
        paintPanel(assistanceClientPanel);
    }//GEN-LAST:event_assistanceClientBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton assingClientBtn;
    private javax.swing.JButton assistanceClientBtn;
    private javax.swing.JButton clientsHistoryBtn;
    private javax.swing.JPanel contentPane;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JButton membershipsBtn;
    private javax.swing.JPanel menuBar;
    private javax.swing.JButton newClientBtn;
    private javax.swing.JButton newEmployeeBtn;
    private javax.swing.JButton newRoutine;
    private javax.swing.JButton registerEquipmentBtn;
    private javax.swing.JButton reportEquipmentBtn;
    private javax.swing.JButton reportsBtn;
    private javax.swing.JButton requestEquipmentBtn;
    private javax.swing.JButton routinesBtn;
    private javax.swing.JButton sendEquipmentBtn;
    private javax.swing.JButton viewClientsBtn;
    // End of variables declaration//GEN-END:variables

    private void paintPanel(JPanel panel) {
        panel.setOpaque(false);
        contentPane.removeAll();
        contentPane.setLayout(new BorderLayout());
        contentPane.add(panel);
        contentPane.repaint();
        contentPane.revalidate();
    }

    private void viewMenuBar() {
        loginPanel.addPropertyChangeListener("validLogin", evt -> {
            boolean status = (boolean) evt.getNewValue();
            menuBar.setVisible(status);

            if (status) {
                int width = (int) Toolkit.getDefaultToolkit().getScreenSize().getWidth();
                int height = (int) Toolkit.getDefaultToolkit().getScreenSize().getHeight();
                this.setSize(width, height);
                if (loginPanel.getRol().equalsIgnoreCase("Administrador")) {
                    this.actionsAdmin();
                    paintPanel(generatedReportPanel);
                } else if (loginPanel.getRol().equalsIgnoreCase("Administrador de Inventario")) {
                    this.actionsInventory();
                    paintPanel(sendEquipmentPanel);
                } else if (loginPanel.getRol().equalsIgnoreCase("Entrenador")) {
                    this.actionsTrainer();
                    paintPanel(assingClientPanel);
                } else if (loginPanel.getRol().equalsIgnoreCase("Recepcionista")) {
                    this.actionsReceptionist();
                    paintPanel(receptionistPanel);
                }
            }
        });
    }

    private void actionsAdmin() {
        // Acciones del Recepcionista
        this.newClientBtn.setVisible(false);
        this.viewClientsBtn.setVisible(false);
        this.clientsHistoryBtn.setVisible(false);
        this.membershipsBtn.setVisible(false);
        this.assistanceClientBtn.setVisible(false);
        // Acciones de inventario
        this.registerEquipmentBtn.setVisible(false);
        this.requestEquipmentBtn.setVisible(false);
        this.sendEquipmentBtn.setVisible(false);
        this.reportEquipmentBtn.setVisible(false);
        // Acciones del entrenador
        this.assingClientBtn.setVisible(false);
        this.routinesBtn.setVisible(false);
        this.newRoutine.setVisible(false);
        //Acciones del administrador
        this.reportsBtn.setVisible(true);
        this.newEmployeeBtn.setVisible(true);
    }

    private void actionsInventory() {
        // Acciones del Recepcionista
        this.newClientBtn.setVisible(false);
        this.viewClientsBtn.setVisible(false);
        this.clientsHistoryBtn.setVisible(false);
        this.membershipsBtn.setVisible(false);
        this.assistanceClientBtn.setVisible(false);
        // Acciones de inventario
        this.registerEquipmentBtn.setVisible(true);
        this.requestEquipmentBtn.setVisible(true);
        this.sendEquipmentBtn.setVisible(true);
        this.reportEquipmentBtn.setVisible(true);
        // Acciones del entrenador
        this.assingClientBtn.setVisible(false);
        this.routinesBtn.setVisible(false);
        this.newRoutine.setVisible(false);
        //Acciones del administrador
        this.reportsBtn.setVisible(false);
        this.newEmployeeBtn.setVisible(false);
    }

    private void actionsTrainer() {
        // Acciones del Recepcionista
        this.newClientBtn.setVisible(false);
        this.viewClientsBtn.setVisible(false);
        this.clientsHistoryBtn.setVisible(false);
        this.membershipsBtn.setVisible(false);
        this.assistanceClientBtn.setVisible(false);
        // Acciones de inventario
        this.registerEquipmentBtn.setVisible(false);
        this.requestEquipmentBtn.setVisible(false);
        this.sendEquipmentBtn.setVisible(false);
        this.reportEquipmentBtn.setVisible(false);
        // Acciones del entrenador
        this.assingClientBtn.setVisible(true);
        this.routinesBtn.setVisible(true);
        this.newRoutine.setVisible(true);
        //Acciones del administrador
        this.reportsBtn.setVisible(false);
        this.newEmployeeBtn.setVisible(false);
    }

    private void actionsReceptionist() {
        // Acciones del Recepcionista
        this.newClientBtn.setVisible(true);
        this.viewClientsBtn.setVisible(true);
        this.clientsHistoryBtn.setVisible(true);
        this.membershipsBtn.setVisible(true);
        this.assistanceClientBtn.setVisible(true);
        // Acciones de inventario
        this.registerEquipmentBtn.setVisible(false);
        this.requestEquipmentBtn.setVisible(false);
        this.sendEquipmentBtn.setVisible(false);
        this.reportEquipmentBtn.setVisible(false);
        // Acciones del entrenador
        this.assingClientBtn.setVisible(false);
        this.routinesBtn.setVisible(false);
        this.newRoutine.setVisible(false);
        //Acciones del administrador
        this.reportsBtn.setVisible(false);
        this.newEmployeeBtn.setVisible(false);
    }

    private void styleMenuBarFlatLaf() {
        menuBar.putClientProperty(FlatClientProperties.STYLE, "background: " + ColorApp.GREEN + ";");

        JButton[] buttons = {
            newClientBtn, viewClientsBtn, assistanceClientBtn, clientsHistoryBtn, membershipsBtn,
            registerEquipmentBtn, requestEquipmentBtn, sendEquipmentBtn, reportEquipmentBtn,
            assingClientBtn, routinesBtn, reportsBtn, newEmployeeBtn, newRoutine, logoutBtn
        };

        for (JButton button : buttons) {
            button.putClientProperty(FlatClientProperties.BUTTON_TYPE, "roundRect");
            button.putClientProperty(FlatClientProperties.STYLE, ""
                    + "arc: 20;"
                    + "font: bold +12;"
                    + "background: " + ColorApp.GREEN + ";"
                    + "foreground: " + ColorApp.WHITE + ";"
                    + "hoverBackground: " + ColorApp.GREEN_DARK + ";"
                    + "pressedBackground: " + ColorApp.GREEN_DARKED + ";"
            );
        }
    }

    class PanelBackground extends JPanel {

        private Image image;

        @Override
        public void paint(Graphics g) {
            image = new ImageIcon(getClass().getResource("/images/BigSportgym.jpg")).getImage();
            g.drawImage(image, 0, 0, getWidth(), getHeight(), this);
            setOpaque(false);
            super.paint(g);
        }
    }

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/IconGym.png"));
        return retValue;
    }
}