package frontend.principal;

import frontend.admin.AdministratorPanel;
import frontend.inventorymanager.InventoryManagerPanel;
import frontend.receptionist.ReceptionistPanel;
import frontend.trainer.TrainerPanel;
import java.awt.BorderLayout;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author michael
 */
public class MainWindow extends javax.swing.JFrame {

    public static final String TITTLE = "Fit - Manager";
    private final PanelBackground panelBackground = new PanelBackground();
    private final LoginPanel loginPanel = new LoginPanel();
    private final AdministratorPanel administratorPanel = new AdministratorPanel();
    private final InventoryManagerPanel inventoryManagerPanel = new InventoryManagerPanel();
    private final ReceptionistPanel receptionistPanel = new ReceptionistPanel();
    private final TrainerPanel trainerPanel = new TrainerPanel();

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        this.setContentPane(panelBackground);
        initComponents();
        this.paintPanel(loginPanel);
        this.setIconImage(getIconImage());
        this.setTitle(TITTLE);
        this.menuBar.setVisible(false);
        this.viewMenuBar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contentPane = new javax.swing.JPanel();
        menuBar = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        newClientBtn = new javax.swing.JMenuItem();
        viewClientsBtn = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        logoutBtn = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 500));

        contentPane.setMinimumSize(new java.awt.Dimension(600, 800));
        contentPane.setOpaque(false);
        contentPane.setLayout(new java.awt.BorderLayout());

        menuBar.setBackground(new java.awt.Color(102, 255, 102));
        menuBar.setForeground(new java.awt.Color(0, 0, 0));

        jMenu2.setBackground(new java.awt.Color(0, 204, 102));
        jMenu2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenu2.setText("Clientes");

        newClientBtn.setText("Nuevo Cliente");
        jMenu2.add(newClientBtn);

        viewClientsBtn.setText("Ver Clientes");
        jMenu2.add(viewClientsBtn);

        menuBar.add(jMenu2);

        jMenu6.setBackground(new java.awt.Color(0, 204, 102));
        jMenu6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenu6.setText("Inventario");

        jMenuItem10.setText("Gestionar Inventario");
        jMenu6.add(jMenuItem10);

        menuBar.add(jMenu6);

        jMenu4.setBackground(new java.awt.Color(0, 204, 102));
        jMenu4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenu4.setText("Empleados");

        jMenuItem3.setText("Administradores");
        jMenu4.add(jMenuItem3);

        jMenuItem5.setText("Administradores de Inventario");
        jMenu4.add(jMenuItem5);

        jMenuItem4.setText("Entrenadores");
        jMenu4.add(jMenuItem4);

        jMenuItem6.setText("Recepcionistas");
        jMenu4.add(jMenuItem6);

        menuBar.add(jMenu4);

        jMenu5.setBackground(new java.awt.Color(0, 204, 102));
        jMenu5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenu5.setText("Rutinas");

        jMenuItem8.setText("Ver Rutinas");
        jMenu5.add(jMenuItem8);

        jMenuItem9.setText("Nueva Rutina");
        jMenu5.add(jMenuItem9);

        menuBar.add(jMenu5);

        jMenu3.setBackground(new java.awt.Color(0, 204, 102));
        jMenu3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenu3.setText("Sucursales");

        jMenuItem7.setText("Ver Sucursales");
        jMenu3.add(jMenuItem7);

        menuBar.add(jMenu3);

        logoutBtn.setBackground(new java.awt.Color(0, 204, 102));
        logoutBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        logoutBtn.setText("Cerrar sesión");
        logoutBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutBtnMouseClicked(evt);
            }
        });
        menuBar.add(logoutBtn);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contentPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1012, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contentPane, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutBtnMouseClicked
        this.menuBar.setVisible(false);
        loginPanel.setValidLogin(false);
        paintPanel(loginPanel);
    }//GEN-LAST:event_logoutBtnMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contentPane;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenu logoutBtn;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem newClientBtn;
    private javax.swing.JMenuItem viewClientsBtn;
    // End of variables declaration//GEN-END:variables

    private void paintPanel(JPanel panel) {
        panel.setOpaque(false);
        contentPane.removeAll();
        contentPane.setLayout(new BorderLayout());
        contentPane.add(panel);
        contentPane.repaint();
        contentPane.revalidate();
    }

    private void viewMenuBar() {
        loginPanel.addPropertyChangeListener("validLogin", evt -> {
            boolean status = (boolean) evt.getNewValue();
            menuBar.setVisible(status);
            
            if (status) {
                if (loginPanel.getRol().equalsIgnoreCase("Administrador")) {
                    paintPanel(administratorPanel);
                } else if (loginPanel.getRol().equalsIgnoreCase("Inventario")) {
                    paintPanel(inventoryManagerPanel);
                } else if (loginPanel.getRol().equalsIgnoreCase("Entrenador")) {
                    paintPanel(trainerPanel);
                } else if (loginPanel.getRol().equalsIgnoreCase("Recepcionista")) {
                    paintPanel(receptionistPanel);
                }
            }
        });
    }

    class PanelBackground extends JPanel {

        private Image image;

        @Override
        public void paint(Graphics g) {
            image = new ImageIcon(getClass().getResource("/images/imageGym.jpg")).getImage();
            g.drawImage(image, 0, 0, getWidth(), getHeight(), this);
            setOpaque(false);
            super.paint(g);
        }
    }

    //CAMBIA EL ICONO EN LA BARRA DE TÍTULO Y BARRA DE TAREAS
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/IconGym.png"));
        return retValue;
    }
}
