package frontend.receptionist;

import backend.util.ColorApp;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author michael
 */
public class NewClientPanel extends javax.swing.JPanel {

    /**
     * Creates new form ReceptionistPanel
     */
    public NewClientPanel() {
        initComponents();
        this.styleComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        addClientBtn = new javax.swing.JButton();
        nameClientTextField = new javax.swing.JTextField();
        addressClientField = new javax.swing.JTextField();
        phoneNumberField = new javax.swing.JTextField();
        phoneEmergencyField = new javax.swing.JTextField();
        trainersListComboBox = new javax.swing.JComboBox<>();

        setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Nuevo Cliente");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(40, 225, 0, 0);
        add(jLabel1, gridBagConstraints);

        jLabel2.setText("Nombre:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(64, 125, 0, 0);
        add(jLabel2, gridBagConstraints);

        jLabel3.setText("Dirección");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(28, 125, 0, 0);
        add(jLabel3, gridBagConstraints);

        jLabel4.setText("Teléfono");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(28, 125, 0, 0);
        add(jLabel4, gridBagConstraints);

        jLabel5.setText("Teléfono de emergencia");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 40, 0, 0);
        add(jLabel5, gridBagConstraints);

        jLabel6.setText("Asignar Entrenador");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(38, 67, 0, 0);
        add(jLabel6, gridBagConstraints);

        addClientBtn.setText("Registrar Cliente");
        addClientBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addClientBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(24, 200, 206, 0);
        add(addClientBtn, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 206;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(57, 60, 0, 0);
        add(nameClientTextField, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 206;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 60, 0, 0);
        add(addressClientField, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 206;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 60, 0, 0);
        add(phoneNumberField, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.ipadx = 206;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 60, 0, 0);
        add(phoneEmergencyField, gridBagConstraints);

        trainersListComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.ipadx = 188;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(31, 60, 0, 0);
        add(trainersListComboBox, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void addClientBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addClientBtnActionPerformed
        this.validRegister();
    }//GEN-LAST:event_addClientBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addClientBtn;
    private javax.swing.JTextField addressClientField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField nameClientTextField;
    private javax.swing.JTextField phoneEmergencyField;
    private javax.swing.JTextField phoneNumberField;
    private javax.swing.JComboBox<String> trainersListComboBox;
    // End of variables declaration//GEN-END:variables

    private void styleComponents() {
        jLabel1.putClientProperty("FlatLaf.style", "font: bold +18; foreground: " + ColorApp.GREEN + ";");

        jLabel2.putClientProperty("FlatLaf.style", "font: 14; foreground: #333333;");
        jLabel3.putClientProperty("FlatLaf.style", "font: 14; foreground: #333333;");
        jLabel4.putClientProperty("FlatLaf.style", "font: 14; foreground: #333333;");
        jLabel5.putClientProperty("FlatLaf.style", "font: 14; foreground: #333333;");
        jLabel6.putClientProperty("FlatLaf.style", "font: 14; foreground: #333333;");

        nameClientTextField.putClientProperty("JTextField.placeholderText", "Ingrese el nombre");
        nameClientTextField.putClientProperty("FlatLaf.style", "arc: 15; focusColor: " + ColorApp.GREEN + "; font: 14;");

        addressClientField.putClientProperty("JTextField.placeholderText", "Ingrese la dirección");
        addressClientField.putClientProperty("FlatLaf.style", "arc: 15; focusColor: " + ColorApp.GREEN + "; font: 14;");

        phoneNumberField.putClientProperty("JTextField.placeholderText", "Ingrese el teléfono");
        phoneNumberField.putClientProperty("FlatLaf.style", "arc: 15; focusColor: " + ColorApp.GREEN + "; font: 14;");

        phoneEmergencyField.putClientProperty("JTextField.placeholderText", "Ingrese el teléfono de emergencia");
        phoneEmergencyField.putClientProperty("FlatLaf.style", "arc: 15; focusColor: " + ColorApp.GREEN + "; font: 14;");

        trainersListComboBox.putClientProperty("FlatLaf.style", "arc: 15; focusColor: " + ColorApp.GREEN + "; font: 14;");

        addClientBtn.putClientProperty("JButton.buttonType", "roundRect");
        addClientBtn.putClientProperty("FlatLaf.style", ""
                + "font: bold +16;"
                + "arc: 20;"
                + "focusWidth: 2;"
                + "background: " + ColorApp.GREEN + ";"
                + "foreground: " + ColorApp.WHITE + ";"
                + "hoverBackground: " + ColorApp.GREEN_DARK + ";"
                + "pressedBackground: " + ColorApp.GREEN_DARKED + ";"
        );
    }

    private void validRegister() {
        boolean validTxt = nameClientTextField.getText().isEmpty() && addressClientField.getText().isEmpty() && phoneNumberField.getText().isEmpty();
        boolean validTxtOp = nameClientTextField.getText().isEmpty() || addressClientField.getText().isEmpty() || phoneNumberField.getText().isEmpty();
        boolean trainerSelected = trainersListComboBox.getSelectedIndex() == 0;

        if (validTxt || trainerSelected || validTxtOp) {
            if (validTxt) {
                JOptionPane.showMessageDialog(this, "Los campos \"Nombre\", \"Teléfono\", \"Teléfono de emergencia\" son datos obligatorios", "Campos vacíos", JOptionPane.INFORMATION_MESSAGE);
                addClientBtn.setBackground(Color.red);
            } else if (trainerSelected) {
                JOptionPane.showMessageDialog(this, "Debe de asignar un entrenador", "Campos vacíos", JOptionPane.INFORMATION_MESSAGE);
                addClientBtn.setBackground(Color.red);
            }
        }
    }
}
