package frontend.admin;

import backend.util.ColorApp;
import com.formdev.flatlaf.FlatClientProperties;
import frontend.admin.clientsreports.MostFrequent;
import frontend.admin.inventoryreports.EquipmentBranchPanel;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Insets;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JSeparator;

/**
 *
 * @author michael
 */
public class GeneratedReportPanel extends javax.swing.JPanel {

    private final MostFrequent mostFrequent = new MostFrequent();
    private final EquipmentBranchPanel equipmentBranchPanel = new EquipmentBranchPanel();

    /**
     * Creates new form AdministratorPanel
     */
    public GeneratedReportPanel() {
        initComponents();
        this.paintPanel(mostFrequent);
        this.styleComponents();
        this.setOpaque(false);
        contentPane.setOpaque(false);
        menuPanel.setOpaque(false);
        jScrollPane1.setOpaque(false);
        jScrollPane1.getViewport().setOpaque(false);

        this.paintPanel(mostFrequent);
        this.styleComponents();
        this.contentPane.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contentPane = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        menuPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        mostClientsBtn = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        mostUsedBtn = new javax.swing.JButton();
        mostFrequentBtn = new javax.swing.JButton();
        higherExpenseBtn = new javax.swing.JButton();
        greaterAssistenceBtn = new javax.swing.JButton();
        moreRoutinesCreatedBtn = new javax.swing.JButton();
        sameTimeBtn = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        moreAdditionalServicesBtn = new javax.swing.JButton();
        moreIncomeBtn = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        GreaterAssistanceBtn = new javax.swing.JButton();
        bestSellingBtn = new javax.swing.JButton();
        membershipIncomeBtn = new javax.swing.JButton();
        paymentsDatesBtn = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        membershipsClientsBtnclie = new javax.swing.JButton();
        mostUsedEquipmentBtn = new javax.swing.JButton();
        greaterOverlapRoutinesBtn = new javax.swing.JButton();
        availablePerBranchBtn = new javax.swing.JButton();
        damagedEquipmentBtn = new javax.swing.JButton();

        contentPane.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setBorder(null);
        jScrollPane1.setColumnHeaderView(null);
        jScrollPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setOpaque(false);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(280, 1590));

        menuPanel.setPreferredSize(new java.awt.Dimension(270, 1588));

        jLabel1.setText("Reporte de clientes");

        mostClientsBtn.setText("Con más clientes");
        mostClientsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostClientsBtnActionPerformed(evt);
            }
        });

        jLabel2.setText("Reporte de enternadores");

        mostUsedBtn.setText("Más utilizados");
        mostUsedBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostUsedBtnActionPerformed(evt);
            }
        });

        mostFrequentBtn.setText("Más frecuentes");
        mostFrequentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostFrequentBtnActionPerformed(evt);
            }
        });

        higherExpenseBtn.setText("Con mayor gasto");
        higherExpenseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                higherExpenseBtnActionPerformed(evt);
            }
        });

        greaterAssistenceBtn.setText("Con mayor asistencia");
        greaterAssistenceBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                greaterAssistenceBtnActionPerformed(evt);
            }
        });

        moreRoutinesCreatedBtn.setText("Más rutinas creadas");
        moreRoutinesCreatedBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moreRoutinesCreatedBtnActionPerformed(evt);
            }
        });

        sameTimeBtn.setText("Con más clientes asignados");
        sameTimeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sameTimeBtnActionPerformed(evt);
            }
        });

        jLabel3.setText("Reporte de sucursales");

        moreAdditionalServicesBtn.setText("Con más servicios adicionales");
        moreAdditionalServicesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moreAdditionalServicesBtnActionPerformed(evt);
            }
        });

        moreIncomeBtn.setText("Con más ingresos");
        moreIncomeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moreIncomeBtnActionPerformed(evt);
            }
        });

        jLabel4.setText("Reporte de membresías y pagos");

        GreaterAssistanceBtn.setText("Con mayor asistencia");
        GreaterAssistanceBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GreaterAssistanceBtnActionPerformed(evt);
            }
        });

        bestSellingBtn.setText("Membresías más vendidas");
        bestSellingBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bestSellingBtnActionPerformed(evt);
            }
        });

        membershipIncomeBtn.setText("Ingresos por membresía");
        membershipIncomeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                membershipIncomeBtnActionPerformed(evt);
            }
        });

        paymentsDatesBtn.setText("Pagos por fechas");
        paymentsDatesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentsDatesBtnActionPerformed(evt);
            }
        });

        jLabel5.setText("Reporte de inventarios");

        membershipsClientsBtnclie.setText("Clientes por membresía");
        membershipsClientsBtnclie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                membershipsClientsBtnclieActionPerformed(evt);
            }
        });

        mostUsedEquipmentBtn.setText("Equipos más utilizados");
        mostUsedEquipmentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostUsedEquipmentBtnActionPerformed(evt);
            }
        });

        greaterOverlapRoutinesBtn.setText("Mayor coincidencia de rutinas");
        greaterOverlapRoutinesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                greaterOverlapRoutinesBtnActionPerformed(evt);
            }
        });

        availablePerBranchBtn.setText("Disponibles por sucursal");
        availablePerBranchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                availablePerBranchBtnActionPerformed(evt);
            }
        });

        damagedEquipmentBtn.setText("Equipos dañados");
        damagedEquipmentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                damagedEquipmentBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuPanelLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(4, 4, 4))
                    .addComponent(mostFrequentBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(higherExpenseBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(greaterAssistenceBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(menuPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(menuPanelLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(4, 4, 4))
                    .addComponent(mostClientsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(moreRoutinesCreatedBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sameTimeBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(moreAdditionalServicesBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                    .addGroup(menuPanelLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(menuPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(moreIncomeBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(GreaterAssistanceBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(menuPanelLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(menuPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(bestSellingBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(membershipIncomeBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(paymentsDatesBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(membershipsClientsBtnclie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(menuPanelLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jSeparator1)
                        .addGap(6, 6, 6))
                    .addGroup(menuPanelLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(mostUsedEquipmentBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(greaterOverlapRoutinesBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(availablePerBranchBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(damagedEquipmentBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mostUsedBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(63, 63, 63))
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(24, 24, 24)
                .addComponent(mostFrequentBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(higherExpenseBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(greaterAssistenceBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                .addGap(32, 32, 32)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(24, 24, 24)
                .addComponent(mostClientsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(moreRoutinesCreatedBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(sameTimeBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(moreAdditionalServicesBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                .addGap(28, 28, 28)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(24, 24, 24)
                .addComponent(moreIncomeBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(GreaterAssistanceBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                .addGap(36, 36, 36)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(24, 24, 24)
                .addComponent(bestSellingBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(membershipIncomeBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(paymentsDatesBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(membershipsClientsBtnclie, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                .addGap(34, 34, 34)
                .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                .addGap(36, 36, 36)
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
                .addGap(24, 24, 24)
                .addComponent(mostUsedEquipmentBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(greaterOverlapRoutinesBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(availablePerBranchBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(damagedEquipmentBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(mostUsedBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                .addGap(6, 6, 6))
        );

        jScrollPane1.setViewportView(menuPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contentPane, javax.swing.GroupLayout.DEFAULT_SIZE, 710, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1597, Short.MAX_VALUE)
            .addComponent(contentPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void mostFrequentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostFrequentBtnActionPerformed
        paintPanel(mostFrequent);
    }//GEN-LAST:event_mostFrequentBtnActionPerformed

    private void higherExpenseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_higherExpenseBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_higherExpenseBtnActionPerformed

    private void greaterAssistenceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_greaterAssistenceBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_greaterAssistenceBtnActionPerformed

    private void mostClientsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostClientsBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mostClientsBtnActionPerformed

    private void moreRoutinesCreatedBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moreRoutinesCreatedBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_moreRoutinesCreatedBtnActionPerformed

    private void sameTimeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sameTimeBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sameTimeBtnActionPerformed

    private void moreAdditionalServicesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moreAdditionalServicesBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_moreAdditionalServicesBtnActionPerformed

    private void moreIncomeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moreIncomeBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_moreIncomeBtnActionPerformed

    private void GreaterAssistanceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GreaterAssistanceBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GreaterAssistanceBtnActionPerformed

    private void bestSellingBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bestSellingBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bestSellingBtnActionPerformed

    private void membershipIncomeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_membershipIncomeBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_membershipIncomeBtnActionPerformed

    private void paymentsDatesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentsDatesBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paymentsDatesBtnActionPerformed

    private void membershipsClientsBtnclieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_membershipsClientsBtnclieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_membershipsClientsBtnclieActionPerformed

    private void mostUsedEquipmentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostUsedEquipmentBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mostUsedEquipmentBtnActionPerformed

    private void greaterOverlapRoutinesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_greaterOverlapRoutinesBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_greaterOverlapRoutinesBtnActionPerformed

    /**
     * Muestra el panel que mostrará el reporte de máquinas por
     * sucursal.
     * @param evt captura los eventos del teclado o mouse.
     */
    private void availablePerBranchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_availablePerBranchBtnActionPerformed
        paintPanel(equipmentBranchPanel);
    }//GEN-LAST:event_availablePerBranchBtnActionPerformed

    private void damagedEquipmentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_damagedEquipmentBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_damagedEquipmentBtnActionPerformed

    private void mostUsedBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostUsedBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mostUsedBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GreaterAssistanceBtn;
    private javax.swing.JButton availablePerBranchBtn;
    private javax.swing.JButton bestSellingBtn;
    private javax.swing.JPanel contentPane;
    private javax.swing.JButton damagedEquipmentBtn;
    private javax.swing.JButton greaterAssistenceBtn;
    private javax.swing.JButton greaterOverlapRoutinesBtn;
    private javax.swing.JButton higherExpenseBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JButton membershipIncomeBtn;
    private javax.swing.JButton membershipsClientsBtnclie;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JButton moreAdditionalServicesBtn;
    private javax.swing.JButton moreIncomeBtn;
    private javax.swing.JButton moreRoutinesCreatedBtn;
    private javax.swing.JButton mostClientsBtn;
    private javax.swing.JButton mostFrequentBtn;
    private javax.swing.JButton mostUsedBtn;
    private javax.swing.JButton mostUsedEquipmentBtn;
    private javax.swing.JButton paymentsDatesBtn;
    private javax.swing.JButton sameTimeBtn;
    // End of variables declaration//GEN-END:variables

    /**
     * Sirve para cambiar la vista que se verá en el contentPane.
     *
     * @param panel es la vista que se mostrará en contentPane de tipo JPanel.
     */
    private void paintPanel(JPanel panel) {
        panel.setOpaque(false);
        contentPane.removeAll();
        contentPane.setLayout(new BorderLayout());
        contentPane.add(panel);
        contentPane.repaint();
        contentPane.revalidate();
    }

    /**
     * Sirve para modificar la vista de los componentes.
     */
    private void styleComponents() {
        jLabel2.setText("<html>Reporte de<br>clientes</html>");
        jLabel2.setText("<html>Reporte de<br>entrenadores</html>");
        jLabel3.setText("<html>Reporte de<br>sucursales</html>");
        jLabel4.setText("<html>Reporte de<br>membresías y pagos</html>");
        jLabel5.setText("<html>Reporte de<br>inventarios</html>");

        jScrollPane1.getVerticalScrollBar().setUnitIncrement(30);
        JLabel[] labels = {jLabel1, jLabel2, jLabel3, jLabel4, jLabel5};
        for (javax.swing.JLabel label : labels) {
            label.putClientProperty("FlatLaf.style",
                    "font: bold +10; foreground: " + ColorApp.GREEN_DARKED + ";");
        }

        JButton[] buttons = {
            mostFrequentBtn, higherExpenseBtn, greaterAssistenceBtn,
            mostClientsBtn, moreRoutinesCreatedBtn, sameTimeBtn, moreAdditionalServicesBtn,
            moreIncomeBtn, GreaterAssistanceBtn,
            bestSellingBtn, membershipIncomeBtn, paymentsDatesBtn, membershipsClientsBtnclie,
            mostUsedEquipmentBtn, greaterOverlapRoutinesBtn, availablePerBranchBtn, damagedEquipmentBtn, mostUsedBtn
        };

        int maxWidth = 0;
        for (JButton button : buttons) {
            button.putClientProperty(FlatClientProperties.BUTTON_TYPE, "roundRect");
            button.putClientProperty(FlatClientProperties.STYLE,
                    "arc: 12;"
                    + "font: +4;"
                    + "background: " + ColorApp.GREEN + ";"
                    + "foreground: " + ColorApp.WHITE + ";"
                    + "hoverBackground: " + ColorApp.GREEN_DARK + ";"
                    + "pressedBackground: " + ColorApp.GREEN_DARKED + ";"
                    + "focusWidth: 1;"
                    + "focusColor: " + ColorApp.GREEN_DARK + ";");
            button.setFocusable(false);

            maxWidth = Math.max(maxWidth, button.getPreferredSize().width);
        }

        int buttonHeight = 30;
        for (JButton button : buttons) {
            Dimension size = button.getPreferredSize();
            button.setPreferredSize(new Dimension(size.width, buttonHeight));
        }

        int indent = 1;
        for (JButton button : buttons) {
            button.setMargin(new Insets(1, indent, 1, 1));
        }

        JSeparator[] separators = {jSeparator1, jSeparator5, jSeparator6, jSeparator7};
        for (JSeparator sep : separators) {
            sep.setForeground(Color.GREEN);
        }
    }
}
