-- Bodega de máquinas de repuesto
INSERT INTO storage_warehouse (warehouse_id, warehouse_name, address, equipment_quantity)
VALUES (uuid_generate_v4(), 'En el oeste de la ciudad', 'Bodega Central', 50);

-- Sucursales
INSERT INTO gym_branch (branch_id, branch_name, branch_address)
VALUES (uuid_generate_v4(), 'Sucursal Central', 'Centro de la ciudad'),
(uuid_generate_v4(), 'Sucursal Norte', 'Al norte de la ciudad'),
(uuid_generate_v4(), 'Sucursal Sur', 'Al sur de la ciudad');

-- Roles
INSERT INTO role (role_id, role_name)
VALUES (uuid_generate_v4(), 'Administrador'),
(uuid_generate_v4(), 'Administrador de Inventario'),
(uuid_generate_v4(), 'Entrenador'),
(uuid_generate_v4(), 'Recepcionista');

-- Empleados
-- Administradores
INSERT INTO employee(employee_id, role_id, branch_id, employee_name, password, contact_phone)
VALUES (uuid_generate_v4(), (SELECT role_id FROM role WHERE role_name = 'Administrador'), (SELECT branch_id FROM gym_branch WHERE branch_name = 'Sucursal Central'), 'Carlos Gómez', 'admincar123','12345678'),
(uuid_generate_v4(), (SELECT role_id FROM role WHERE role_name = 'Administrador'), (SELECT branch_id FROM gym_branch WHERE branch_name = 'Sucursal Norte'), 'Nathalie Monzón', 'adminnath123','87654321'),
(uuid_generate_v4(), (SELECT role_id FROM role WHERE role_name = 'Administrador'), (SELECT branch_id FROM gym_branch WHERE branch_name = 'Sucursal Sur'), 'Miguel Ramírez', 'adminmig123','24681357')

INSERT INTO employee(employee_id, role_id, branch_id, employee_name, password, contact_phone)
VALUES 
-- Sucursal Central
(uuid_generate_v4(), (SELECT role_id FROM role WHERE role_name = 'Entrenador'), (SELECT branch_id FROM gym_branch WHERE branch_name = 'Sucursal Central'), 'Alejandro Torres', 'ale123', '15550101'),
(uuid_generate_v4(), (SELECT role_id FROM role WHERE role_name = 'Entrenador'), (SELECT branch_id FROM gym_branch WHERE branch_name = 'Sucursal Central'), 'Camila Rojas', 'cam123', '25550102'),
(uuid_generate_v4(), (SELECT role_id FROM role WHERE role_name = 'Entrenador'), (SELECT branch_id FROM gym_branch WHERE branch_name = 'Sucursal Central'), 'Daniel Méndez', 'dan123', '35550103'),
(uuid_generate_v4(), (SELECT role_id FROM role WHERE role_name = 'Entrenador'), (SELECT branch_id FROM gym_branch WHERE branch_name = 'Sucursal Central'), 'Valeria Castillo', 'val123', '45550104'),
(uuid_generate_v4(), (SELECT role_id FROM role WHERE role_name = 'Entrenador'), (SELECT branch_id FROM gym_branch WHERE branch_name = 'Sucursal Central'), 'Sebastián López', 'seb123', '55550105'),
(uuid_generate_v4(), (SELECT role_id FROM role WHERE role_name = 'Entrenador'), (SELECT branch_id FROM gym_branch WHERE branch_name = 'Sucursal Central'), 'Mariana Sánchez', 'mar123', '65550106'),
(uuid_generate_v4(), (SELECT role_id FROM role WHERE role_name = 'Entrenador'), (SELECT branch_id FROM gym_branch WHERE branch_name = 'Sucursal Central'), 'Javier Pérez', 'jav123', '75550107'),
(uuid_generate_v4(), (SELECT role_id FROM role WHERE role_name = 'Entrenador'), (SELECT branch_id FROM gym_branch WHERE branch_name = 'Sucursal Central'), 'Natalia Ramírez', 'nat123', '85550108'),
(uuid_generate_v4(), (SELECT role_id FROM role WHERE role_name = 'Entrenador'), (SELECT branch_id FROM gym_branch WHERE branch_name = 'Sucursal Central'), 'Rodrigo Fernández', 'rod123', '95550109'),
(uuid_generate_v4(), (SELECT role_id FROM role WHERE role_name = 'Entrenador'), (SELECT branch_id FROM gym_branch WHERE branch_name = 'Sucursal Central'), 'Andrea Morales', 'andrea123', '05550110'),
(uuid_generate_v4(), (SELECT role_id FROM role WHERE role_name = 'Entrenador'), (SELECT branch_id FROM gym_branch WHERE branch_name = 'Sucursal Central'), 'Luis Gutiérrez', 'luis123', '15550111'),
(uuid_generate_v4(), (SELECT role_id FROM role WHERE role_name = 'Entrenador'), (SELECT branch_id FROM gym_branch WHERE branch_name = 'Sucursal Central'), 'Paola Díaz', 'pao123', '25550112'),
(uuid_generate_v4(), (SELECT role_id FROM role WHERE role_name = 'Entrenador'), (SELECT branch_id FROM gym_branch WHERE branch_name = 'Sucursal Central'), 'Carlos Hernández', 'carlos123', '35550113'),
(uuid_generate_v4(), (SELECT role_id FROM role WHERE role_name = 'Entrenador'), (SELECT branch_id FROM gym_branch WHERE branch_name = 'Sucursal Central'), 'Gabriela Vargas', 'gab123', '45550114'),
(uuid_generate_v4(), (SELECT role_id FROM role WHERE role_name = 'Entrenador'), (SELECT branch_id FROM gym_branch WHERE branch_name = 'Sucursal Central'), 'Mauricio Aguilar', 'mau123', '55550115'),
(uuid_generate_v4(), (SELECT role_id FROM role WHERE role_name = 'Entrenador'), (SELECT branch_id FROM gym_branch WHERE branch_name = 'Sucursal Central'), 'Karen Soto', 'karen123', '65550116'),
(uuid_generate_v4(), (SELECT role_id FROM role WHERE role_name = 'Entrenador'), (SELECT branch_id FROM gym_branch WHERE branch_name = 'Sucursal Central'), 'Ricardo Jiménez', 'ric123', '57550117'),
(uuid_generate_v4(), (SELECT role_id FROM role WHERE role_name = 'Entrenador'), (SELECT branch_id FROM gym_branch WHERE branch_name = 'Sucursal Central'), 'Daniela Flores', 'dani123', '85550118'),
(uuid_generate_v4(), (SELECT role_id FROM role WHERE role_name = 'Entrenador'), (SELECT branch_id FROM gym_branch WHERE branch_name = 'Sucursal Central'), 'Francisco Molina', 'fran123', '95550119'),
(uuid_generate_v4(), (SELECT role_id FROM role WHERE role_name = 'Entrenador'), (SELECT branch_id FROM gym_branch WHERE branch_name = 'Sucursal Central'), 'Lorena Castro', 'lor123', '56550120'),
(uuid_generate_v4(), (SELECT role_id FROM role WHERE role_name = 'Entrenador'), (SELECT branch_id FROM gym_branch WHERE branch_name = 'Sucursal Central'), 'Eduardo Ruiz', 'edu123', '55550121'),
(uuid_generate_v4(), (SELECT role_id FROM role WHERE role_name = 'Entrenador'), (SELECT branch_id FROM gym_branch WHERE branch_name = 'Sucursal Central'), 'Fernanda Silva', 'fer123', '95550122'),
(uuid_generate_v4(), (SELECT role_id FROM role WHERE role_name = 'Entrenador'), (SELECT branch_id FROM gym_branch WHERE branch_name = 'Sucursal Central'), 'Jorge Martínez', 'jor123', '85550123'),
(uuid_generate_v4(), (SELECT role_id FROM role WHERE role_name = 'Entrenador'), (SELECT branch_id FROM gym_branch WHERE branch_name = 'Sucursal Central'), 'Sofía Bravo', 'sof123', '75550124'),
(uuid_generate_v4(), (SELECT role_id FROM role WHERE role_name = 'Entrenador'), (SELECT branch_id FROM gym_branch WHERE branch_name = 'Sucursal Central'), 'Andrés Vega', 'andres123', '65550125'),
(uuid_generate_v4(), (SELECT role_id FROM role WHERE role_name = 'Administrador de Inventario'), (SELECT branch_id FROM gym_branch WHERE branch_name = 'Sucursal Central'), 'Fernando Aguilar', 'fern123', '55550126'),
(uuid_generate_v4(), (SELECT role_id FROM role WHERE role_name = 'Administrador de Inventario'), (SELECT branch_id FROM gym_branch WHERE branch_name = 'Sucursal Central'), 'Laura Mendoza', 'lau123', '45550127'),
(uuid_generate_v4(), (SELECT role_id FROM role WHERE role_name = 'Administrador de Inventario'), (SELECT branch_id FROM gym_branch WHERE branch_name = 'Sucursal Central'), 'Javier Ortiz', 'javi123', '35550128'),
(uuid_generate_v4(), (SELECT role_id FROM role WHERE role_name = 'Administrador de Inventario'), (SELECT branch_id FROM gym_branch WHERE branch_name = 'Sucursal Central'), 'Claudia Herrera', 'clau123', '25550129'),
(uuid_generate_v4(), (SELECT role_id FROM role WHERE role_name = 'Administrador de Inventario'), (SELECT branch_id FROM gym_branch WHERE branch_name = 'Sucursal Central'), 'Fernando Aguilar', 'ferando123', '15550130'),
(uuid_generate_v4(), (SELECT role_id FROM role WHERE role_name = 'Recepcionista'), (SELECT branch_id FROM gym_branch WHERE branch_name = 'Sucursal Central'), 'Ricardo Peña', 'ricardo123', '55050131'),
(uuid_generate_v4(), (SELECT role_id FROM role WHERE role_name = 'Recepcionista'), (SELECT branch_id FROM gym_branch WHERE branch_name = 'Sucursal Central'), 'Isabel Torres', 'isa123', '55500132'),
(uuid_generate_v4(), (SELECT role_id FROM role WHERE role_name = 'Recepcionista'), (SELECT branch_id FROM gym_branch WHERE branch_name = 'Sucursal Central'), 'Martín Rivas', 'martin123', '55530133'),
-- Sucursal Norte
(uuid_generate_v4(), (SELECT role_id FROM role WHERE role_name = 'Entrenador'), (SELECT branch_id FROM gym_branch WHERE branch_name = 'Sucursal Norte'), 'Diego Salazar', 'die123', '55500201'),
(uuid_generate_v4(), (SELECT role_id FROM role WHERE role_name = 'Entrenador'), (SELECT branch_id FROM gym_branch WHERE branch_name = 'Sucursal Norte'), 'Paula Miranda', 'pau123', '55510202'),
(uuid_generate_v4(), (SELECT role_id FROM role WHERE role_name = 'Entrenador'), (SELECT branch_id FROM gym_branch WHERE branch_name = 'Sucursal Norte'), 'Tomás Beltrán', 'tom123', '55520203'),
(uuid_generate_v4(), (SELECT role_id FROM role WHERE role_name = 'Entrenador'), (SELECT branch_id FROM gym_branch WHERE branch_name = 'Sucursal Norte'), 'Elisa Ramírez', 'eli123', '55530204'),
(uuid_generate_v4(), (SELECT role_id FROM role WHERE role_name = 'Entrenador'), (SELECT branch_id FROM gym_branch WHERE branch_name = 'Sucursal Norte'), 'Nicolás Cordero', 'nic123', '55540205'),
(uuid_generate_v4(), (SELECT role_id FROM role WHERE role_name = 'Entrenador'), (SELECT branch_id FROM gym_branch WHERE branch_name = 'Sucursal Norte'), 'Juliana Pacheco', 'jul123', '55550206'),
(uuid_generate_v4(), (SELECT role_id FROM role WHERE role_name = 'Entrenador'), (SELECT branch_id FROM gym_branch WHERE branch_name = 'Sucursal Norte'), 'Matías Figueroa', 'mat123', '55560207'),
(uuid_generate_v4(), (SELECT role_id FROM role WHERE role_name = 'Entrenador'), (SELECT branch_id FROM gym_branch WHERE branch_name = 'Sucursal Norte'), 'Carolina Herrera', 'car123', '55570208'),
(uuid_generate_v4(), (SELECT role_id FROM role WHERE role_name = 'Entrenador'), (SELECT branch_id FROM gym_branch WHERE branch_name = 'Sucursal Norte'), 'Sebastían Andrade', 'sebas123', '55580209'),
(uuid_generate_v4(), (SELECT role_id FROM role WHERE role_name = 'Entrenador'), (SELECT branch_id FROM gym_branch WHERE branch_name = 'Sucursal Norte'), 'Valentina Soto', 'vale123', '55590210'),
(uuid_generate_v4(), (SELECT role_id FROM role WHERE role_name = 'Entrenador'), (SELECT branch_id FROM gym_branch WHERE branch_name = 'Sucursal Norte'), 'Andrés Cifuentes', 'andres1234', '55500211'),
(uuid_generate_v4(), (SELECT role_id FROM role WHERE role_name = 'Entrenador'), (SELECT branch_id FROM gym_branch WHERE branch_name = 'Sucursal Norte'), 'Mariana López', 'mari123', '55510212'),
(uuid_generate_v4(), (SELECT role_id FROM role WHERE role_name = 'Entrenador'), (SELECT branch_id FROM gym_branch WHERE branch_name = 'Sucursal Norte'), 'Felipe Duarte', 'fel123', '55520213'),
(uuid_generate_v4(), (SELECT role_id FROM role WHERE role_name = 'Entrenador'), (SELECT branch_id FROM gym_branch WHERE branch_name = 'Sucursal Norte'), 'Lorena Medina', 'lor1234', '55530214'),
(uuid_generate_v4(), (SELECT role_id FROM role WHERE role_name = 'Entrenador'), (SELECT branch_id FROM gym_branch WHERE branch_name = 'Sucursal Norte'), 'Gabriel Torres', 'gab1234', '55540215'),
(uuid_generate_v4(), (SELECT role_id FROM role WHERE role_name = 'Administrador de Inventario'), (SELECT branch_id FROM gym_branch WHERE branch_name = 'Sucursal Norte'), 'Patricia Vega', 'pat123', '55550216'),
(uuid_generate_v4(), (SELECT role_id FROM role WHERE role_name = 'Administrador de Inventario'), (SELECT branch_id FROM gym_branch WHERE branch_name = 'Sucursal Norte'), 'Hugo Sánchez', 'hug123', '55560217'),
(uuid_generate_v4(), (SELECT role_id FROM role WHERE role_name = 'Administrador de Inventario'), (SELECT branch_id FROM gym_branch WHERE branch_name = 'Sucursal Norte'), 'Adriana Molina', 'adri123', '55570218'),
(uuid_generate_v4(), (SELECT role_id FROM role WHERE role_name = 'Recepcionista'), (SELECT branch_id FROM gym_branch WHERE branch_name = 'Sucursal Norte'), 'Daniel Rojas', 'dani123', '55580219'),
(uuid_generate_v4(), (SELECT role_id FROM role WHERE role_name = 'Recepcionista'), (SELECT branch_id FROM gym_branch WHERE branch_name = 'Sucursal Norte'), 'Jorge Salinas', 'jorge123', '55590220'),
-- Sucursal Sur
(uuid_generate_v4(), (SELECT role_id FROM role WHERE role_name = 'Entrenador'), (SELECT branch_id FROM gym_branch WHERE branch_name = 'Sucursal Sur'), 'Mauricio Ríos', 'pass123', '5550301'),
(uuid_generate_v4(), (SELECT role_id FROM role WHERE role_name = 'Entrenador'), (SELECT branch_id FROM gym_branch WHERE branch_name = 'Sucursal Sur'), 'Valeria Paredes', 'pass123', '5550302'),
(uuid_generate_v4(), (SELECT role_id FROM role WHERE role_name = 'Entrenador'), (SELECT branch_id FROM gym_branch WHERE branch_name = 'Sucursal Sur'), 'Carlos León', 'pass123', '5550303'),
(uuid_generate_v4(), (SELECT role_id FROM role WHERE role_name = 'Entrenador'), (SELECT branch_id FROM gym_branch WHERE branch_name = 'Sucursal Sur'), 'Fernanda Cabrera', 'pass123', '55500304'),
(uuid_generate_v4(), (SELECT role_id FROM role WHERE role_name = 'Entrenador'), (SELECT branch_id FROM gym_branch WHERE branch_name = 'Sucursal Sur'), 'Ricardo Orozco', 'pass123', '55540305'),
(uuid_generate_v4(), (SELECT role_id FROM role WHERE role_name = 'Entrenador'), (SELECT branch_id FROM gym_branch WHERE branch_name = 'Sucursal Sur'), 'Camila Fajardo', 'pass123', '55570306'),
(uuid_generate_v4(), (SELECT role_id FROM role WHERE role_name = 'Entrenador'), (SELECT branch_id FROM gym_branch WHERE branch_name = 'Sucursal Sur'), 'Andrés Jiménez', 'pass123', '55580307'),
(uuid_generate_v4(), (SELECT role_id FROM role WHERE role_name = 'Entrenador'), (SELECT branch_id FROM gym_branch WHERE branch_name = 'Sucursal Sur'), 'Natalia Guzmán', 'pass123', '55590308'),
(uuid_generate_v4(), (SELECT role_id FROM role WHERE role_name = 'Entrenador'), (SELECT branch_id FROM gym_branch WHERE branch_name = 'Sucursal Sur'), 'Felipe Carrillo', 'pass123', '55530309'),
(uuid_generate_v4(), (SELECT role_id FROM role WHERE role_name = 'Entrenador'), (SELECT branch_id FROM gym_branch WHERE branch_name = 'Sucursal Sur'), 'Lorena Salcedo', 'pass123', '55560310'),
(uuid_generate_v4(), (SELECT role_id FROM role WHERE role_name = 'Administrador de Inventario'), (SELECT branch_id FROM gym_branch WHERE branch_name = 'Sucursal Sur'), 'Sandra Morales', 'pass123', '55540311'),
(uuid_generate_v4(), (SELECT role_id FROM role WHERE role_name = 'Administrador de Inventario'), (SELECT branch_id FROM gym_branch WHERE branch_name = 'Sucursal Sur'), 'Víctor Ramírez', 'pass123', '55590312'),
(uuid_generate_v4(), (SELECT role_id FROM role WHERE role_name = 'Recepcionista'), (SELECT branch_id FROM gym_branch WHERE branch_name = 'Sucursal Sur'), 'Alejandro Castillo', 'pass123', '55530313');

-- Tipos de membresía
INSERT INTO membership_type (membership_type_id, membership_type_name)
VALUES (uuid_generate_v4(), 'Básico'),
(uuid_generate_v4(), 'Premium'),
(uuid_generate_v4(), 'VIP');

-- Clientes
INSERT INTO client (client_id, name, phone_number, contact_emergency, trainer_id, membership_type_id)
VALUES
(uuid_generate_v4(), 'Andrea López', '55501001', '55501002', (SELECT employee_id FROM employee WHERE role_id=(SELECT role_id FROM role WHERE role_name='Entrenador') ORDER BY random() LIMIT 1), (SELECT membership_type_id FROM membership_type WHERE membership_type_name='Básico')),
(uuid_generate_v4(), 'Diego Martínez', '55501003', '55501004', (SELECT employee_id FROM employee WHERE role_id=(SELECT role_id FROM role WHERE role_name='Entrenador') ORDER BY random() LIMIT 1), (SELECT membership_type_id FROM membership_type WHERE membership_type_name='Básico')),
(uuid_generate_v4(), 'Valentina Herrera', '55501005', '55501006', (SELECT employee_id FROM employee WHERE role_id=(SELECT role_id FROM role WHERE role_name='Entrenador') ORDER BY random() LIMIT 1), (SELECT membership_type_id FROM membership_type WHERE membership_type_name='Básico')),
(uuid_generate_v4(), 'Sebastián González', '55501007', '55501008', (SELECT employee_id FROM employee WHERE role_id=(SELECT role_id FROM role WHERE role_name='Entrenador') ORDER BY random() LIMIT 1), (SELECT membership_type_id FROM membership_type WHERE membership_type_name='Básico')),
(uuid_generate_v4(), 'Camila Ramírez', '55501009', '55501010', (SELECT employee_id FROM employee WHERE role_id=(SELECT role_id FROM role WHERE role_name='Entrenador') ORDER BY random() LIMIT 1), (SELECT membership_type_id FROM membership_type WHERE membership_type_name='Básico')),
(uuid_generate_v4(), 'Nicolás Fernández', '55501011', '55501012', (SELECT employee_id FROM employee WHERE role_id=(SELECT role_id FROM role WHERE role_name='Entrenador') ORDER BY random() LIMIT 1), (SELECT membership_type_id FROM membership_type WHERE membership_type_name='Básico')),
(uuid_generate_v4(), 'Mariana Torres', '55501013', '55501014', (SELECT employee_id FROM employee WHERE role_id=(SELECT role_id FROM role WHERE role_name='Entrenador') ORDER BY random() LIMIT 1), (SELECT membership_type_id FROM membership_type WHERE membership_type_name='Básico')),
(uuid_generate_v4(), 'Javier Morales', '55501015', '55501016', (SELECT employee_id FROM employee WHERE role_id=(SELECT role_id FROM role WHERE role_name='Entrenador') ORDER BY random() LIMIT 1), (SELECT membership_type_id FROM membership_type WHERE membership_type_name='Básico')),
(uuid_generate_v4(), 'Isabella Castro', '55501017', '55501018', (SELECT employee_id FROM employee WHERE role_id=(SELECT role_id FROM role WHERE role_name='Entrenador') ORDER BY random() LIMIT 1), (SELECT membership_type_id FROM membership_type WHERE membership_type_name='Básico')),
(uuid_generate_v4(), 'Rodrigo Sánchez', '55501019', '55501020', (SELECT employee_id FROM employee WHERE role_id=(SELECT role_id FROM role WHERE role_name='Entrenador') ORDER BY random() LIMIT 1), (SELECT membership_type_id FROM membership_type WHERE membership_type_name='Básico')),
(uuid_generate_v4(), 'Daniela Flores', '55501021', '55501022', (SELECT employee_id FROM employee WHERE role_id=(SELECT role_id FROM role WHERE role_name='Entrenador') ORDER BY random() LIMIT 1), (SELECT membership_type_id FROM membership_type WHERE membership_type_name='Básico')),
(uuid_generate_v4(), 'Alejandro Rivas', '55501023', '55501024', (SELECT employee_id FROM employee WHERE role_id=(SELECT role_id FROM role WHERE role_name='Entrenador') ORDER BY random() LIMIT 1), (SELECT membership_type_id FROM membership_type WHERE membership_type_name='Básico')),
(uuid_generate_v4(), 'Paula Jiménez', '55501025', '55501026', (SELECT employee_id FROM employee WHERE role_id=(SELECT role_id FROM role WHERE role_name='Entrenador') ORDER BY random() LIMIT 1), (SELECT membership_type_id FROM membership_type WHERE membership_type_name='Básico')),
(uuid_generate_v4(), 'Matías Díaz', '55501027', '55501028', (SELECT employee_id FROM employee WHERE role_id=(SELECT role_id FROM role WHERE role_name='Entrenador') ORDER BY random() LIMIT 1), (SELECT membership_type_id FROM membership_type WHERE membership_type_name='Básico')),
(uuid_generate_v4(), 'Lorena Pérez', '55501029', '55501030', (SELECT employee_id FROM employee WHERE role_id=(SELECT role_id FROM role WHERE role_name='Entrenador') ORDER BY random() LIMIT 1), (SELECT membership_type_id FROM membership_type WHERE membership_type_name='Básico')),
(uuid_generate_v4(), 'Carlos Gutiérrez', '55501031', '55501032', (SELECT employee_id FROM employee WHERE role_id=(SELECT role_id FROM role WHERE role_name='Entrenador') ORDER BY random() LIMIT 1), (SELECT membership_type_id FROM membership_type WHERE membership_type_name='Básico')),
(uuid_generate_v4(), 'Fernanda Vega', '55501033', '55501034', (SELECT employee_id FROM employee WHERE role_id=(SELECT role_id FROM role WHERE role_name='Entrenador') ORDER BY random() LIMIT 1), (SELECT membership_type_id FROM membership_type WHERE membership_type_name='Básico')),
(uuid_generate_v4(), 'Felipe Molina', '55501035', '55501036', (SELECT employee_id FROM employee WHERE role_id=(SELECT role_id FROM role WHERE role_name='Entrenador') ORDER BY random() LIMIT 1), (SELECT membership_type_id FROM membership_type WHERE membership_type_name='Básico')),
(uuid_generate_v4(), 'Natalia Herrera', '55501037', '55501038', (SELECT employee_id FROM employee WHERE role_id=(SELECT role_id FROM role WHERE role_name='Entrenador') ORDER BY random() LIMIT 1), (SELECT membership_type_id FROM membership_type WHERE membership_type_name='Básico')),
(uuid_generate_v4(), 'Tomás Ramírez', '55501039', '55501040', (SELECT employee_id FROM employee WHERE role_id=(SELECT role_id FROM role WHERE role_name='Entrenador') ORDER BY random() LIMIT 1), (SELECT membership_type_id FROM membership_type WHERE membership_type_name='Básico')),
(uuid_generate_v4(), 'Gabriela Soto', '55501041', '55501042', (SELECT employee_id FROM employee WHERE role_id=(SELECT role_id FROM role WHERE role_name='Entrenador') ORDER BY random() LIMIT 1), (SELECT membership_type_id FROM membership_type WHERE membership_type_name='Básico')),
(uuid_generate_v4(), 'Andrés Salazar', '55501043', '55501044', (SELECT employee_id FROM employee WHERE role_id=(SELECT role_id FROM role WHERE role_name='Entrenador') ORDER BY random() LIMIT 1), (SELECT membership_type_id FROM membership_type WHERE membership_type_name='Básico')),
(uuid_generate_v4(), 'Sofía Bravo', '55501045', '55501046', (SELECT employee_id FROM employee WHERE role_id=(SELECT role_id FROM role WHERE role_name='Entrenador') ORDER BY random() LIMIT 1), (SELECT membership_type_id FROM membership_type WHERE membership_type_name='Básico')),
(uuid_generate_v4(), 'Luis Cordero', '55501047', '55501048', (SELECT employee_id FROM employee WHERE role_id=(SELECT role_id FROM role WHERE role_name='Entrenador') ORDER BY random() LIMIT 1), (SELECT membership_type_id FROM membership_type WHERE membership_type_name='Básico')),
(uuid_generate_v4(), 'Karen Mendoza', '55501049', '55501050', (SELECT employee_id FROM employee WHERE role_id=(SELECT role_id FROM role WHERE role_name='Entrenador') ORDER BY random() LIMIT 1), (SELECT membership_type_id FROM membership_type WHERE membership_type_name='Básico')),
(uuid_generate_v4(), 'Ricardo Aguilar', '55501051', '55501052', (SELECT employee_id FROM employee WHERE role_id=(SELECT role_id FROM role WHERE role_name='Entrenador') ORDER BY random() LIMIT 1), (SELECT membership_type_id FROM membership_type WHERE membership_type_name='Básico')),
(uuid_generate_v4(), 'Juliana Ortíz', '55501053', '55501054', (SELECT employee_id FROM employee WHERE role_id=(SELECT role_id FROM role WHERE role_name='Entrenador') ORDER BY random() LIMIT 1), (SELECT membership_type_id FROM membership_type WHERE membership_type_name='Básico')),
(uuid_generate_v4(), 'Eduardo Ramírez', '55501055', '55501056', (SELECT employee_id FROM employee WHERE role_id=(SELECT role_id FROM role WHERE role_name='Entrenador') ORDER BY random() LIMIT 1), (SELECT membership_type_id FROM membership_type WHERE membership_type_name='Básico')),
(uuid_generate_v4(), 'Isabel Cabrera', '55501057', '55501058', (SELECT employee_id FROM employee WHERE role_id=(SELECT role_id FROM role WHERE role_name='Entrenador') ORDER BY random() LIMIT 1), (SELECT membership_type_id FROM membership_type WHERE membership_type_name='Básico')),
(uuid_generate_v4(), 'Martín Castillo', '55501059', '55501060', (SELECT employee_id FROM employee WHERE role_id=(SELECT role_id FROM role WHERE role_name='Entrenador') ORDER BY random() LIMIT 1), (SELECT membership_type_id FROM membership_type WHERE membership_type_name='Básico')),
(uuid_generate_v4(), 'Samuel Torres', '55502001', '55502002', (SELECT employee_id FROM employee WHERE role_id=(SELECT role_id FROM role WHERE role_name='Entrenador') ORDER BY random() LIMIT 1), (SELECT membership_type_id FROM membership_type WHERE membership_type_name='Premium')),
(uuid_generate_v4(), 'Valeria Paredes', '55502003', '55502004', (SELECT employee_id FROM employee WHERE role_id=(SELECT role_id FROM role WHERE role_name='Entrenador') ORDER BY random() LIMIT 1), (SELECT membership_type_id FROM membership_type WHERE membership_type_name='Premium')),
(uuid_generate_v4(), 'Diego Rojas', '55502005', '55502006', (SELECT employee_id FROM employee WHERE role_id=(SELECT role_id FROM role WHERE role_name='Entrenador') ORDER BY random() LIMIT 1), (SELECT membership_type_id FROM membership_type WHERE membership_type_name='Premium')),
(uuid_generate_v4(), 'Camila Vargas', '55502007', '55502008', (SELECT employee_id FROM employee WHERE role_id=(SELECT role_id FROM role WHERE role_name='Entrenador') ORDER BY random() LIMIT 1), (SELECT membership_type_id FROM membership_type WHERE membership_type_name='Premium')),
(uuid_generate_v4(), 'Andrés Castillo', '55502009', '55502010', (SELECT employee_id FROM employee WHERE role_id=(SELECT role_id FROM role WHERE role_name='Entrenador') ORDER BY random() LIMIT 1), (SELECT membership_type_id FROM membership_type WHERE membership_type_name='Premium')),
(uuid_generate_v4(), 'Mariana Soto', '55502011', '55502012', (SELECT employee_id FROM employee WHERE role_id=(SELECT role_id FROM role WHERE role_name='Entrenador') ORDER BY random() LIMIT 1), (SELECT membership_type_id FROM membership_type WHERE membership_type_name='Premium')),
(uuid_generate_v4(), 'Nicolás Ramírez', '55502013', '55502014', (SELECT employee_id FROM employee WHERE role_id=(SELECT role_id FROM role WHERE role_name='Entrenador') ORDER BY random() LIMIT 1), (SELECT membership_type_id FROM membership_type WHERE membership_type_name='Premium')),
(uuid_generate_v4(), 'Juliana Morales', '55502015', '55502016', (SELECT employee_id FROM employee WHERE role_id=(SELECT role_id FROM role WHERE role_name='Entrenador') ORDER BY random() LIMIT 1), (SELECT membership_type_id FROM membership_type WHERE membership_type_name='Premium')),
(uuid_generate_v4(), 'Felipe Herrera', '55502017', '55502018', (SELECT employee_id FROM employee WHERE role_id=(SELECT role_id FROM role WHERE role_name='Entrenador') ORDER BY random() LIMIT 1), (SELECT membership_type_id FROM membership_type WHERE membership_type_name='Premium')),
(uuid_generate_v4(), 'Isabella Cruz', '55502019', '55502020', (SELECT employee_id FROM employee WHERE role_id=(SELECT role_id FROM role WHERE role_name='Entrenador') ORDER BY random() LIMIT 1), (SELECT membership_type_id FROM membership_type WHERE membership_type_name='Premium')),
(uuid_generate_v4(), 'Javier Guzmán', '55502021', '55502022', (SELECT employee_id FROM employee WHERE role_id=(SELECT role_id FROM role WHERE role_name='Entrenador') ORDER BY random() LIMIT 1), (SELECT membership_type_id FROM membership_type WHERE membership_type_name='Premium')),
(uuid_generate_v4(), 'Lorena Medina', '55502023', '55502024', (SELECT employee_id FROM employee WHERE role_id=(SELECT role_id FROM role WHERE role_name='Entrenador') ORDER BY random() LIMIT 1), (SELECT membership_type_id FROM membership_type WHERE membership_type_name='Premium')),
(uuid_generate_v4(), 'Alejandro Figueroa', '55502025', '55502026', (SELECT employee_id FROM employee WHERE role_id=(SELECT role_id FROM role WHERE role_name='Entrenador') ORDER BY random() LIMIT 1), (SELECT membership_type_id FROM membership_type WHERE membership_type_name='Premium')),
(uuid_generate_v4(), 'Sofía Jiménez', '55502027', '55502028', (SELECT employee_id FROM employee WHERE role_id=(SELECT role_id FROM role WHERE role_name='Entrenador') ORDER BY random() LIMIT 1), (SELECT membership_type_id FROM membership_type WHERE membership_type_name='Premium')),
(uuid_generate_v4(), 'Carlos Peña', '55502029', '55502030', (SELECT employee_id FROM employee WHERE role_id=(SELECT role_id FROM role WHERE role_name='Entrenador') ORDER BY random() LIMIT 1), (SELECT membership_type_id FROM membership_type WHERE membership_type_name='Premium')),
(uuid_generate_v4(), 'Fernanda López', '55502031', '55502032', (SELECT employee_id FROM employee WHERE role_id=(SELECT role_id FROM role WHERE role_name='Entrenador') ORDER BY random() LIMIT 1), (SELECT membership_type_id FROM membership_type WHERE membership_type_name='Premium')),
(uuid_generate_v4(), 'Ricardo Duarte', '55502033', '55502034', (SELECT employee_id FROM employee WHERE role_id=(SELECT role_id FROM role WHERE role_name='Entrenador') ORDER BY random() LIMIT 1), (SELECT membership_type_id FROM membership_type WHERE membership_type_name='Premium')),
(uuid_generate_v4(), 'Gabriela Cordero', '55502035', '55502036', (SELECT employee_id FROM employee WHERE role_id=(SELECT role_id FROM role WHERE role_name='Entrenador') ORDER BY random() LIMIT 1), (SELECT membership_type_id FROM membership_type WHERE membership_type_name='Premium')),
(uuid_generate_v4(), 'Matías Salazar', '55502037', '55502038', (SELECT employee_id FROM employee WHERE role_id=(SELECT role_id FROM role WHERE role_name='Entrenador') ORDER BY random() LIMIT 1), (SELECT membership_type_id FROM membership_type WHERE membership_type_name='Premium')),
(uuid_generate_v4(), 'Daniela Bravo', '55502039', '55502040', (SELECT employee_id FROM employee WHERE role_id=(SELECT role_id FROM role WHERE role_name='Entrenador') ORDER BY random() LIMIT 1), (SELECT membership_type_id FROM membership_type WHERE membership_type_name='Premium')),
(uuid_generate_v4(), 'Tomás Ortíz', '55503001', '55503002', (SELECT employee_id FROM employee WHERE role_id=(SELECT role_id FROM role WHERE role_name='Entrenador') ORDER BY random() LIMIT 1), (SELECT membership_type_id FROM membership_type WHERE membership_type_name='VIP')),
(uuid_generate_v4(), 'Paula Fernández', '55503003', '55503004', (SELECT employee_id FROM employee WHERE role_id=(SELECT role_id FROM role WHERE role_name='Entrenador') ORDER BY random() LIMIT 1), (SELECT membership_type_id FROM membership_type WHERE membership_type_name='VIP')),
(uuid_generate_v4(), 'Luis Vega', '55503005', '55503006', (SELECT employee_id FROM employee WHERE role_id=(SELECT role_id FROM role WHERE role_name='Entrenador') ORDER BY random() LIMIT 1), (SELECT membership_type_id FROM membership_type WHERE membership_type_name='VIP')),
(uuid_generate_v4(), 'Valentina Ríos', '55503007', '55503008', (SELECT employee_id FROM employee WHERE role_id=(SELECT role_id FROM role WHERE role_name='Entrenador') ORDER BY random() LIMIT 1), (SELECT membership_type_id FROM membership_type WHERE membership_type_name='VIP')),
(uuid_generate_v4(), 'Mauricio Aguilar', '55503009', '55503010', (SELECT employee_id FROM employee WHERE role_id=(SELECT role_id FROM role WHERE role_name='Entrenador') ORDER BY random() LIMIT 1), (SELECT membership_type_id FROM membership_type WHERE membership_type_name='VIP')),
(uuid_generate_v4(), 'Isabel Pacheco', '55503011', '55503012', (SELECT employee_id FROM employee WHERE role_id=(SELECT role_id FROM role WHERE role_name='Entrenador') ORDER BY random() LIMIT 1), (SELECT membership_type_id FROM membership_type WHERE membership_type_name='VIP')),
(uuid_generate_v4(), 'Jorge Castillo', '55503013', '55503014', (SELECT employee_id FROM employee WHERE role_id=(SELECT role_id FROM role WHERE role_name='Entrenador') ORDER BY random() LIMIT 1), (SELECT membership_type_id FROM membership_type WHERE membership_type_name='VIP')),
(uuid_generate_v4(), 'Carolina Ramírez', '55503015', '55503016', (SELECT employee_id FROM employee WHERE role_id=(SELECT role_id FROM role WHERE role_name='Entrenador') ORDER BY random() LIMIT 1), (SELECT membership_type_id FROM membership_type WHERE membership_type_name='VIP')),
(uuid_generate_v4(), 'Francisco Herrera', '55503017', '55503018', (SELECT employee_id FROM employee WHERE role_id=(SELECT role_id FROM role WHERE role_name='Entrenador') ORDER BY random() LIMIT 1), (SELECT membership_type_id FROM membership_type WHERE membership_type_name='VIP')),
(uuid_generate_v4(), 'Natalia Silva', '55503019', '55503020', (SELECT employee_id FROM employee WHERE role_id=(SELECT role_id FROM role WHERE role_name='Entrenador') ORDER BY random() LIMIT 1), (SELECT membership_type_id FROM membership_type WHERE membership_type_name='VIP'));

-- Tipos de máquinas
INSERT INTO machine_type (type_id, type_name, description) VALUES
(uuid_generate_v4(), 'Caminadora', 'Mejora la resistencia cardiovascular y fortalecer músculos de piernas y glúteos, quemar grasa, y facilitar la recuperación de lesiones'),
(uuid_generate_v4(), 'Bicicleta Estática', 'Bicicleta fija de resistencia ajustable'),
(uuid_generate_v4(), 'Máquina Elíptica', 'Permite un entrenamiento cardiovascular de bajo impacto para todo el cuerpo, combinando el movimiento de una caminadora y una bicicleta estática'),
(uuid_generate_v4(), 'Remadora', 'Simula el movimiento de remar en el agua para un entrenamiento completo de cuerpo entero que fortalece el sistema cardiovascular, las piernas, la espalda y los brazos'),
(uuid_generate_v4(), 'Máquina de Press de Pecho', 'Se utiliza para fortalecer los músculos pectorales, los hombros y los tríceps de manera controlada y segura'),
(uuid_generate_v4(), 'Máquina de Press Inclinado', 'Para trabajar el pectoral superior, el hombro y el tríceps'),
(uuid_generate_v4(), 'Poleas', 'Para realizar ejercicios de fuerza y resistencia que trabajan diversos grupos musculares como bíceps, tríceps, hombros y espalda'),
(uuid_generate_v4(), 'Prensa de piernas', 'Permite trabajar la fuerza de manera controlada en el tren inferior (cuádriceps, isquiotibiales y glúteos) y estabilizando la espalda, siendo una alternativa más segura que la sentadilla para la zona lumbar'),
(uuid_generate_v4(), 'Máquina de extensión de pierna', 'Se enfoca principalmente en los cuádriceps'),
(uuid_generate_v4(), 'Máquina de curl de pierna', 'Para trabajar los isquiotibiales, es decir, los músculos de la parte posterior del muslo'),
(uuid_generate_v4(), 'Máquina de abductores de hack squal', 'Es una sentadilla guiada que también trabaja los cuádriceps y glúteos'),
(uuid_generate_v4(), 'Press de hombros con martillo', 'Para trabajar principalmente los hombros, enfocándose en los deltoides.'),
(uuid_generate_v4(), 'Elevaciones laterales', 'Trabaja principalmente el músculo responsable de la anchura de los hombros y el movimiento lateral'),
(uuid_generate_v4(), 'Máquina de Bíceps', 'Para ejercitar los bíceps dándoles más definición y volumen, también aporta fortaleciendo el tren superior'),
(uuid_generate_v4(), 'Prensa de Tríceps con Barra', 'Para el desarrollo de los músculos de la parte posterior de los brazos'),
(uuid_generate_v4(), 'Máquina de Abdominales', 'Para realizar crunch abdominal con carga guiada, lo que permite una activación precisa y controlada del core, ideal para entrenamientos de fuerza y tonificación abdominal'),
(uuid_generate_v4(), 'Banco Abdominal', 'Para fortalecer los músculos abdominales y mejorar la estabilidad del core'),
(uuid_generate_v4(), 'Banco Plano', 'Distribuye el trabajo uniformemente por todo el pecho y también trabaja los tríceps y los hombres'),
(uuid_generate_v4(), 'Banco Inclinado', 'Permite realizar ejercicios de empuje con mayor énfasis en la parte superior del pectoral y hombros'),
(uuid_generate_v4(), 'Banco Declinado', 'Trabaja principalmente la parte inferior del pectoral mayor'),
(uuid_generate_v4(), 'Máquina Smith', 'Sirve para levantar pesas de forma segura y mantener una buena postura'),
(uuid_generate_v4(), 'Rack de Sentadillas', 'Trabaja espalda baja, abdomen, flexores de la cadera y hombros, trabaja caso el cuerpo completo'),
(uuid_generate_v4(), 'Rack de Pesas', 'Funciona como un soporte o "jaula" para realizar ejercicios con barra, sentadillas y press de banca'),
(uuid_generate_v4(), 'Cuerda de Batalla', 'Para un entrenamientode cuerpo completo que mejora la fuerza, resistencia y coordinación'),
(uuid_generate_v4(), 'Kettlebells', 'Sirve para entrenar fuerza y cardio'),
(uuid_generate_v4(), 'Balón Medicinal', 'Para aumentar fuerza, potencia, resistencia y coordinación'),
(uuid_generate_v4(), 'TRX', 'Utiliza el propio peso corporal para ofrecer resistencia en cientos de ejercicios, fortaleciendo el cuerpo entero, mejora equilibrio, coordinación, flexibilidad y fuerza del core'),
(uuid_generate_v4(), 'Máquina de Gemelos', 'Permite realizar elevaciones de pantorrillas de forma controlada y efectiva'),
(uuid_generate_v4(), 'Máquina de Glúteos', 'Se enfoca en fortalecer y tonificar los músculos de la zona glútea y el tren inferior, incluyendo el glúteo mayor y menor, los isquiotibiales y, en algunos casos, los abductores'),
(uuid_generate_v4(), 'Stepper', 'ejercita principalmente los músculos de la parte inferior del cuerpo y puede ser un excelente equipo cardiovascular para hacaer bombear el corazón');

-- Máquinas de ejercicio en sucursal central
INSERT INTO exercise_machine (machine_id, machine_status, status_description, location_id, type_id) VALUES
(uuid_generate_v4(), TRUE, 'Disponible', '1bc82d79-b42d-4771-9287-31788ec40e39', (SELECT type_id FROM machine_type WHERE type_name = 'Caminadora')),
(uuid_generate_v4(), TRUE, 'Disponible', '1bc82d79-b42d-4771-9287-31788ec40e39', (SELECT type_id FROM machine_type WHERE type_name = 'Caminadora')),
(uuid_generate_v4(), TRUE, 'Disponible', '1bc82d79-b42d-4771-9287-31788ec40e39', (SELECT type_id FROM machine_type WHERE type_name = 'Caminadora')),
(uuid_generate_v4(), TRUE, 'Disponible', '1bc82d79-b42d-4771-9287-31788ec40e39', (SELECT type_id FROM machine_type WHERE type_name = 'Caminadora')),
(uuid_generate_v4(), TRUE, 'Disponible', '1bc82d79-b42d-4771-9287-31788ec40e39', (SELECT type_id FROM machine_type WHERE type_name = 'Bicicleta Estática')),
(uuid_generate_v4(), TRUE, 'Disponible', '1bc82d79-b42d-4771-9287-31788ec40e39', (SELECT type_id FROM machine_type WHERE type_name = 'Bicicleta Estática')),
(uuid_generate_v4(), TRUE, 'Disponible', '1bc82d79-b42d-4771-9287-31788ec40e39', (SELECT type_id FROM machine_type WHERE type_name = 'Bicicleta Estática')),
(uuid_generate_v4(), TRUE, 'Disponible', '1bc82d79-b42d-4771-9287-31788ec40e39', (SELECT type_id FROM machine_type WHERE type_name = 'Bicicleta Estática')),
(uuid_generate_v4(), TRUE, 'Disponible', '1bc82d79-b42d-4771-9287-31788ec40e39', (SELECT type_id FROM machine_type WHERE type_name = 'Bicicleta Estática')),
(uuid_generate_v4(), TRUE, 'Disponible', '1bc82d79-b42d-4771-9287-31788ec40e39', (SELECT type_id FROM machine_type WHERE type_name = 'Bicicleta Estática')),
(uuid_generate_v4(), TRUE, 'Disponible', '1bc82d79-b42d-4771-9287-31788ec40e39', (SELECT type_id FROM machine_type WHERE type_name = 'Bicicleta Estática')),
(uuid_generate_v4(), TRUE, 'Disponible', '1bc82d79-b42d-4771-9287-31788ec40e39', (SELECT type_id FROM machine_type WHERE type_name = 'Bicicleta Estática')),
(uuid_generate_v4(), TRUE, 'Disponible', '1bc82d79-b42d-4771-9287-31788ec40e39', (SELECT type_id FROM machine_type WHERE type_name = 'Bicicleta Estática')),
(uuid_generate_v4(), TRUE, 'Disponible', '1bc82d79-b42d-4771-9287-31788ec40e39', (SELECT type_id FROM machine_type WHERE type_name = 'Bicicleta Estática')),
(uuid_generate_v4(), TRUE, 'Disponible', '1bc82d79-b42d-4771-9287-31788ec40e39', (SELECT type_id FROM machine_type WHERE type_name = 'Remadora')),
(uuid_generate_v4(), TRUE, 'Disponible', '1bc82d79-b42d-4771-9287-31788ec40e39', (SELECT type_id FROM machine_type WHERE type_name = 'Remadora')),
(uuid_generate_v4(), TRUE, 'Disponible', '1bc82d79-b42d-4771-9287-31788ec40e39', (SELECT type_id FROM machine_type WHERE type_name = 'Remadora')),
(uuid_generate_v4(), TRUE, 'Disponible', '1bc82d79-b42d-4771-9287-31788ec40e39', (SELECT type_id FROM machine_type WHERE type_name = 'Máquina de Press de Pecho')),
(uuid_generate_v4(), TRUE, 'Disponible', '1bc82d79-b42d-4771-9287-31788ec40e39', (SELECT type_id FROM machine_type WHERE type_name = 'Máquina de Press de Pecho')),
(uuid_generate_v4(), TRUE, 'Disponible', '1bc82d79-b42d-4771-9287-31788ec40e39', (SELECT type_id FROM machine_type WHERE type_name = 'Máquina de Press de Pecho')),
(uuid_generate_v4(), TRUE, 'Disponible', '1bc82d79-b42d-4771-9287-31788ec40e39', (SELECT type_id FROM machine_type WHERE type_name = 'Máquina de Press Inclinado')),
(uuid_generate_v4(), TRUE, 'Disponible', '1bc82d79-b42d-4771-9287-31788ec40e39', (SELECT type_id FROM machine_type WHERE type_name = 'Máquina de Press Inclinado')),
(uuid_generate_v4(), TRUE, 'Disponible', '1bc82d79-b42d-4771-9287-31788ec40e39', (SELECT type_id FROM machine_type WHERE type_name = 'Máquina de Press Inclinado')),
(uuid_generate_v4(), TRUE, 'Disponible', '1bc82d79-b42d-4771-9287-31788ec40e39', (SELECT type_id FROM machine_type WHERE type_name = 'Máquina de Press Inclinado')),
(uuid_generate_v4(), TRUE, 'Disponible', '1bc82d79-b42d-4771-9287-31788ec40e39', (SELECT type_id FROM machine_type WHERE type_name = 'Poleas')),
(uuid_generate_v4(), TRUE, 'Disponible', '1bc82d79-b42d-4771-9287-31788ec40e39', (SELECT type_id FROM machine_type WHERE type_name = 'Poleas')),
(uuid_generate_v4(), TRUE, 'Disponible', '1bc82d79-b42d-4771-9287-31788ec40e39', (SELECT type_id FROM machine_type WHERE type_name = 'Poleas')),
(uuid_generate_v4(), TRUE, 'Disponible', '1bc82d79-b42d-4771-9287-31788ec40e39', (SELECT type_id FROM machine_type WHERE type_name = 'Poleas')),
(uuid_generate_v4(), TRUE, 'Disponible', '1bc82d79-b42d-4771-9287-31788ec40e39', (SELECT type_id FROM machine_type WHERE type_name = 'Poleas')),
(uuid_generate_v4(), TRUE, 'Disponible', '1bc82d79-b42d-4771-9287-31788ec40e39', (SELECT type_id FROM machine_type WHERE type_name = 'Prensa de piernas')),
(uuid_generate_v4(), TRUE, 'Disponible', '1bc82d79-b42d-4771-9287-31788ec40e39', (SELECT type_id FROM machine_type WHERE type_name = 'Prensa de piernas')),
(uuid_generate_v4(), TRUE, 'Disponible', '1bc82d79-b42d-4771-9287-31788ec40e39', (SELECT type_id FROM machine_type WHERE type_name = 'Prensa de piernas')),
(uuid_generate_v4(), TRUE, 'Disponible', '1bc82d79-b42d-4771-9287-31788ec40e39', (SELECT type_id FROM machine_type WHERE type_name = 'Prensa de piernas')),
(uuid_generate_v4(), TRUE, 'Disponible', '1bc82d79-b42d-4771-9287-31788ec40e39', (SELECT type_id FROM machine_type WHERE type_name = 'Prensa de piernas')),
(uuid_generate_v4(), TRUE, 'Disponible', '1bc82d79-b42d-4771-9287-31788ec40e39', (SELECT type_id FROM machine_type WHERE type_name = 'Máquina de extensión de pierna')),
(uuid_generate_v4(), TRUE, 'Disponible', '1bc82d79-b42d-4771-9287-31788ec40e39', (SELECT type_id FROM machine_type WHERE type_name = 'Máquina de extensión de pierna')),
(uuid_generate_v4(), TRUE, 'Disponible', '1bc82d79-b42d-4771-9287-31788ec40e39', (SELECT type_id FROM machine_type WHERE type_name = 'Máquina de extensión de pierna')),
(uuid_generate_v4(), TRUE, 'Disponible', '1bc82d79-b42d-4771-9287-31788ec40e39', (SELECT type_id FROM machine_type WHERE type_name = 'Máquina de extensión de pierna')),
(uuid_generate_v4(), TRUE, 'Disponible', '1bc82d79-b42d-4771-9287-31788ec40e39', (SELECT type_id FROM machine_type WHERE type_name = 'Máquina de curl de pierna')),
(uuid_generate_v4(), TRUE, 'Disponible', '1bc82d79-b42d-4771-9287-31788ec40e39', (SELECT type_id FROM machine_type WHERE type_name = 'Máquina de curl de pierna')),
(uuid_generate_v4(), TRUE, 'Disponible', '1bc82d79-b42d-4771-9287-31788ec40e39', (SELECT type_id FROM machine_type WHERE type_name = 'Máquina de curl de pierna')),
(uuid_generate_v4(), TRUE, 'Disponible', '1bc82d79-b42d-4771-9287-31788ec40e39', (SELECT type_id FROM machine_type WHERE type_name = 'Máquina de abductores de hack squal')),
(uuid_generate_v4(), TRUE, 'Disponible', '1bc82d79-b42d-4771-9287-31788ec40e39', (SELECT type_id FROM machine_type WHERE type_name = 'Máquina de abductores de hack squal')),
(uuid_generate_v4(), TRUE, 'Disponible', '1bc82d79-b42d-4771-9287-31788ec40e39', (SELECT type_id FROM machine_type WHERE type_name = 'Máquina de abductores de hack squal')),
(uuid_generate_v4(), TRUE, 'Disponible', '1bc82d79-b42d-4771-9287-31788ec40e39', (SELECT type_id FROM machine_type WHERE type_name = 'Press de hombros con martillo')),
(uuid_generate_v4(), TRUE, 'Disponible', '1bc82d79-b42d-4771-9287-31788ec40e39', (SELECT type_id FROM machine_type WHERE type_name = 'Press de hombros con martillo')),
(uuid_generate_v4(), TRUE, 'Disponible', '1bc82d79-b42d-4771-9287-31788ec40e39', (SELECT type_id FROM machine_type WHERE type_name = 'Elevaciones laterales')),
(uuid_generate_v4(), TRUE, 'Disponible', '1bc82d79-b42d-4771-9287-31788ec40e39', (SELECT type_id FROM machine_type WHERE type_name = 'Elevaciones laterales')),
(uuid_generate_v4(), TRUE, 'Disponible', '1bc82d79-b42d-4771-9287-31788ec40e39', (SELECT type_id FROM machine_type WHERE type_name = 'Elevaciones laterales'));

-- Máquinas de ejercicio en sucursal sur
INSERT INTO exercise_machine (machine_id, machine_status, status_description, location_id, type_id) VALUES
(uuid_generate_v4(), TRUE, 'Disponible', '23dc45dd-3b6b-42ed-851d-560ea9462d77', (SELECT type_id FROM machine_type WHERE type_name = 'Caminadora')),
(uuid_generate_v4(), TRUE, 'Disponible', '23dc45dd-3b6b-42ed-851d-560ea9462d77', (SELECT type_id FROM machine_type WHERE type_name = 'Caminadora')),
(uuid_generate_v4(), TRUE, 'Disponible', '23dc45dd-3b6b-42ed-851d-560ea9462d77', (SELECT type_id FROM machine_type WHERE type_name = 'Caminadora')),
(uuid_generate_v4(), TRUE, 'Disponible', '23dc45dd-3b6b-42ed-851d-560ea9462d77', (SELECT type_id FROM machine_type WHERE type_name = 'Banco Inclinado')),
(uuid_generate_v4(), TRUE, 'Disponible', '23dc45dd-3b6b-42ed-851d-560ea9462d77', (SELECT type_id FROM machine_type WHERE type_name = 'Bicicleta Estática')),
(uuid_generate_v4(), TRUE, 'Disponible', '23dc45dd-3b6b-42ed-851d-560ea9462d77', (SELECT type_id FROM machine_type WHERE type_name = 'Bicicleta Estática')),
(uuid_generate_v4(), TRUE, 'Disponible', '23dc45dd-3b6b-42ed-851d-560ea9462d77', (SELECT type_id FROM machine_type WHERE type_name = 'Bicicleta Estática')),
(uuid_generate_v4(), TRUE, 'Disponible', '23dc45dd-3b6b-42ed-851d-560ea9462d77', (SELECT type_id FROM machine_type WHERE type_name = 'Banco Declinado')),
(uuid_generate_v4(), TRUE, 'Disponible', '23dc45dd-3b6b-42ed-851d-560ea9462d77', (SELECT type_id FROM machine_type WHERE type_name = 'Máquina Elíptica')),
(uuid_generate_v4(), TRUE, 'Disponible', '23dc45dd-3b6b-42ed-851d-560ea9462d77', (SELECT type_id FROM machine_type WHERE type_name = 'Máquina Elíptica')),
(uuid_generate_v4(), TRUE, 'Disponible', '23dc45dd-3b6b-42ed-851d-560ea9462d77', (SELECT type_id FROM machine_type WHERE type_name = 'Stepper')),
(uuid_generate_v4(), TRUE, 'Disponible', '23dc45dd-3b6b-42ed-851d-560ea9462d77', (SELECT type_id FROM machine_type WHERE type_name = 'Remadora')),
(uuid_generate_v4(), TRUE, 'Disponible', '23dc45dd-3b6b-42ed-851d-560ea9462d77', (SELECT type_id FROM machine_type WHERE type_name = 'Remadora')),
(uuid_generate_v4(), TRUE, 'Disponible', '23dc45dd-3b6b-42ed-851d-560ea9462d77', (SELECT type_id FROM machine_type WHERE type_name = 'Máquina Smith')),
(uuid_generate_v4(), TRUE, 'Disponible', '23dc45dd-3b6b-42ed-851d-560ea9462d77', (SELECT type_id FROM machine_type WHERE type_name = 'Máquina de Press de Pecho')),
(uuid_generate_v4(), TRUE, 'Disponible', '23dc45dd-3b6b-42ed-851d-560ea9462d77', (SELECT type_id FROM machine_type WHERE type_name = 'Máquina de Press de Pecho')),
(uuid_generate_v4(), TRUE, 'Disponible', '23dc45dd-3b6b-42ed-851d-560ea9462d77', (SELECT type_id FROM machine_type WHERE type_name = 'Máquina de Glúteos')),
(uuid_generate_v4(), TRUE, 'Disponible', '23dc45dd-3b6b-42ed-851d-560ea9462d77', (SELECT type_id FROM machine_type WHERE type_name = 'Máquina de Press Inclinado')),
(uuid_generate_v4(), TRUE, 'Disponible', '23dc45dd-3b6b-42ed-851d-560ea9462d77', (SELECT type_id FROM machine_type WHERE type_name = 'Rack de Pesas')),
(uuid_generate_v4(), TRUE, 'Disponible', '23dc45dd-3b6b-42ed-851d-560ea9462d77', (SELECT type_id FROM machine_type WHERE type_name = 'Rack de Sentadillas')),
(uuid_generate_v4(), TRUE, 'Disponible', '23dc45dd-3b6b-42ed-851d-560ea9462d77', (SELECT type_id FROM machine_type WHERE type_name = 'Poleas')),
(uuid_generate_v4(), TRUE, 'Disponible', '23dc45dd-3b6b-42ed-851d-560ea9462d77', (SELECT type_id FROM machine_type WHERE type_name = 'Poleas')),
(uuid_generate_v4(), TRUE, 'Disponible', '23dc45dd-3b6b-42ed-851d-560ea9462d77', (SELECT type_id FROM machine_type WHERE type_name = 'Kettlebells')),
(uuid_generate_v4(), TRUE, 'Disponible', '23dc45dd-3b6b-42ed-851d-560ea9462d77', (SELECT type_id FROM machine_type WHERE type_name = 'Prensa de piernas')),
(uuid_generate_v4(), TRUE, 'Disponible', '23dc45dd-3b6b-42ed-851d-560ea9462d77', (SELECT type_id FROM machine_type WHERE type_name = 'Prensa de piernas')),
(uuid_generate_v4(), TRUE, 'Disponible', '23dc45dd-3b6b-42ed-851d-560ea9462d77', (SELECT type_id FROM machine_type WHERE type_name = 'Cuerda de Batalla')),
(uuid_generate_v4(), TRUE, 'Disponible', '23dc45dd-3b6b-42ed-851d-560ea9462d77', (SELECT type_id FROM machine_type WHERE type_name = 'Máquina de extensión de pierna')),
(uuid_generate_v4(), TRUE, 'Disponible', '23dc45dd-3b6b-42ed-851d-560ea9462d77', (SELECT type_id FROM machine_type WHERE type_name = 'Máquina de extensión de pierna')),
(uuid_generate_v4(), TRUE, 'Disponible', '23dc45dd-3b6b-42ed-851d-560ea9462d77', (SELECT type_id FROM machine_type WHERE type_name = 'TRX')),
(uuid_generate_v4(), TRUE, 'Disponible', '23dc45dd-3b6b-42ed-851d-560ea9462d77', (SELECT type_id FROM machine_type WHERE type_name = 'Máquina de curl de pierna')),
(uuid_generate_v4(), TRUE, 'Disponible', '23dc45dd-3b6b-42ed-851d-560ea9462d77', (SELECT type_id FROM machine_type WHERE type_name = 'Balón Medicinal')),
(uuid_generate_v4(), TRUE, 'Disponible', '23dc45dd-3b6b-42ed-851d-560ea9462d77', (SELECT type_id FROM machine_type WHERE type_name = 'Máquina de abductores de hack squal')),
(uuid_generate_v4(), TRUE, 'Disponible', '23dc45dd-3b6b-42ed-851d-560ea9462d77', (SELECT type_id FROM machine_type WHERE type_name = 'Máquina de abductores de hack squal')),
(uuid_generate_v4(), TRUE, 'Disponible', '23dc45dd-3b6b-42ed-851d-560ea9462d77', (SELECT type_id FROM machine_type WHERE type_name = 'Press de hombros con martillo')),
(uuid_generate_v4(), TRUE, 'Disponible', '23dc45dd-3b6b-42ed-851d-560ea9462d77', (SELECT type_id FROM machine_type WHERE type_name = 'Press de hombros con martillo')),
(uuid_generate_v4(), TRUE, 'Disponible', '23dc45dd-3b6b-42ed-851d-560ea9462d77', (SELECT type_id FROM machine_type WHERE type_name = 'Máquina de Gemelos')),
(uuid_generate_v4(), TRUE, 'Disponible', '23dc45dd-3b6b-42ed-851d-560ea9462d77', (SELECT type_id FROM machine_type WHERE type_name = 'Elevaciones laterales')),
(uuid_generate_v4(), TRUE, 'Disponible', '23dc45dd-3b6b-42ed-851d-560ea9462d77', (SELECT type_id FROM machine_type WHERE type_name = 'Elevaciones laterales')),
(uuid_generate_v4(), TRUE, 'Disponible', '23dc45dd-3b6b-42ed-851d-560ea9462d77', (SELECT type_id FROM machine_type WHERE type_name = 'Máquina de Bíceps')),
(uuid_generate_v4(), TRUE, 'Disponible', '23dc45dd-3b6b-42ed-851d-560ea9462d77', (SELECT type_id FROM machine_type WHERE type_name = 'Máquina de Bíceps')),
(uuid_generate_v4(), TRUE, 'Disponible', '23dc45dd-3b6b-42ed-851d-560ea9462d77', (SELECT type_id FROM machine_type WHERE type_name = 'Prensa de Tríceps con Barra')),
(uuid_generate_v4(), TRUE, 'Disponible', '23dc45dd-3b6b-42ed-851d-560ea9462d77', (SELECT type_id FROM machine_type WHERE type_name = 'Prensa de Tríceps con Barra')),
(uuid_generate_v4(), TRUE, 'Disponible', '23dc45dd-3b6b-42ed-851d-560ea9462d77', (SELECT type_id FROM machine_type WHERE type_name = 'Máquina de Abdominales')),
(uuid_generate_v4(), TRUE, 'Disponible', '23dc45dd-3b6b-42ed-851d-560ea9462d77', (SELECT type_id FROM machine_type WHERE type_name = 'Máquina de Abdominales')),
(uuid_generate_v4(), TRUE, 'Disponible', '23dc45dd-3b6b-42ed-851d-560ea9462d77', (SELECT type_id FROM machine_type WHERE type_name = 'Banco Abdominal')),
(uuid_generate_v4(), TRUE, 'Disponible', '23dc45dd-3b6b-42ed-851d-560ea9462d77', (SELECT type_id FROM machine_type WHERE type_name = 'Banco Abdominal')),
(uuid_generate_v4(), TRUE, 'Disponible', '23dc45dd-3b6b-42ed-851d-560ea9462d77', (SELECT type_id FROM machine_type WHERE type_name = 'Banco Plano')),
(uuid_generate_v4(), TRUE, 'Disponible', '23dc45dd-3b6b-42ed-851d-560ea9462d77', (SELECT type_id FROM machine_type WHERE type_name = 'Banco Plano')),
(uuid_generate_v4(), TRUE, 'Disponible', '23dc45dd-3b6b-42ed-851d-560ea9462d77', (SELECT type_id FROM machine_type WHERE type_name = 'Máquina de Bíceps')),
(uuid_generate_v4(), TRUE, 'Disponible', '23dc45dd-3b6b-42ed-851d-560ea9462d77', (SELECT type_id FROM machine_type WHERE type_name = 'Prensa de piernas'));

-- Máquinas en sucursal norte
INSERT INTO exercise_machine (machine_id, machine_status, status_description, location_id, type_id) VALUES
(uuid_generate_v4(), TRUE, 'Disponible', '004146d3-9f13-4eab-982f-c55ee7176d83', (SELECT type_id FROM machine_type WHERE type_name = 'Caminadora')),
(uuid_generate_v4(), TRUE, 'Disponible', '004146d3-9f13-4eab-982f-c55ee7176d83', (SELECT type_id FROM machine_type WHERE type_name = 'Caminadora')),
(uuid_generate_v4(), TRUE, 'Disponible', '004146d3-9f13-4eab-982f-c55ee7176d83', (SELECT type_id FROM machine_type WHERE type_name = 'Caminadora')),
(uuid_generate_v4(), TRUE, 'Disponible', '004146d3-9f13-4eab-982f-c55ee7176d83', (SELECT type_id FROM machine_type WHERE type_name = 'Banco Inclinado')),
(uuid_generate_v4(), TRUE, 'Disponible', '004146d3-9f13-4eab-982f-c55ee7176d83', (SELECT type_id FROM machine_type WHERE type_name = 'Bicicleta Estática')),
(uuid_generate_v4(), TRUE, 'Disponible', '004146d3-9f13-4eab-982f-c55ee7176d83', (SELECT type_id FROM machine_type WHERE type_name = 'Bicicleta Estática')),
(uuid_generate_v4(), TRUE, 'Disponible', '004146d3-9f13-4eab-982f-c55ee7176d83', (SELECT type_id FROM machine_type WHERE type_name = 'Bicicleta Estática')),
(uuid_generate_v4(), TRUE, 'Disponible', '004146d3-9f13-4eab-982f-c55ee7176d83', (SELECT type_id FROM machine_type WHERE type_name = 'Banco Declinado')),
(uuid_generate_v4(), TRUE, 'Disponible', '004146d3-9f13-4eab-982f-c55ee7176d83', (SELECT type_id FROM machine_type WHERE type_name = 'Máquina Elíptica')),
(uuid_generate_v4(), TRUE, 'Disponible', '004146d3-9f13-4eab-982f-c55ee7176d83', (SELECT type_id FROM machine_type WHERE type_name = 'Máquina Elíptica')),
(uuid_generate_v4(), TRUE, 'Disponible', '004146d3-9f13-4eab-982f-c55ee7176d83', (SELECT type_id FROM machine_type WHERE type_name = 'Stepper')),
(uuid_generate_v4(), TRUE, 'Disponible', '004146d3-9f13-4eab-982f-c55ee7176d83', (SELECT type_id FROM machine_type WHERE type_name = 'Remadora')),
(uuid_generate_v4(), TRUE, 'Disponible', '004146d3-9f13-4eab-982f-c55ee7176d83', (SELECT type_id FROM machine_type WHERE type_name = 'Remadora')),
(uuid_generate_v4(), TRUE, 'Disponible', '004146d3-9f13-4eab-982f-c55ee7176d83', (SELECT type_id FROM machine_type WHERE type_name = 'Máquina Smith')),
(uuid_generate_v4(), TRUE, 'Disponible', '004146d3-9f13-4eab-982f-c55ee7176d83', (SELECT type_id FROM machine_type WHERE type_name = 'Máquina de Press de Pecho')),
(uuid_generate_v4(), TRUE, 'Disponible', '004146d3-9f13-4eab-982f-c55ee7176d83', (SELECT type_id FROM machine_type WHERE type_name = 'Máquina de Press de Pecho')),
(uuid_generate_v4(), TRUE, 'Disponible', '004146d3-9f13-4eab-982f-c55ee7176d83', (SELECT type_id FROM machine_type WHERE type_name = 'Máquina de Glúteos')),
(uuid_generate_v4(), TRUE, 'Disponible', '004146d3-9f13-4eab-982f-c55ee7176d83', (SELECT type_id FROM machine_type WHERE type_name = 'Máquina de Press Inclinado')),
(uuid_generate_v4(), TRUE, 'Disponible', '004146d3-9f13-4eab-982f-c55ee7176d83', (SELECT type_id FROM machine_type WHERE type_name = 'Rack de Pesas')),
(uuid_generate_v4(), TRUE, 'Disponible', '004146d3-9f13-4eab-982f-c55ee7176d83', (SELECT type_id FROM machine_type WHERE type_name = 'Rack de Sentadillas')),
(uuid_generate_v4(), TRUE, 'Disponible', '004146d3-9f13-4eab-982f-c55ee7176d83', (SELECT type_id FROM machine_type WHERE type_name = 'Poleas')),
(uuid_generate_v4(), TRUE, 'Disponible', '004146d3-9f13-4eab-982f-c55ee7176d83', (SELECT type_id FROM machine_type WHERE type_name = 'Poleas')),
(uuid_generate_v4(), TRUE, 'Disponible', '004146d3-9f13-4eab-982f-c55ee7176d83', (SELECT type_id FROM machine_type WHERE type_name = 'Kettlebells')),
(uuid_generate_v4(), TRUE, 'Disponible', '004146d3-9f13-4eab-982f-c55ee7176d83', (SELECT type_id FROM machine_type WHERE type_name = 'Prensa de piernas')),
(uuid_generate_v4(), TRUE, 'Disponible', '004146d3-9f13-4eab-982f-c55ee7176d83', (SELECT type_id FROM machine_type WHERE type_name = 'Prensa de piernas')),
(uuid_generate_v4(), TRUE, 'Disponible', '004146d3-9f13-4eab-982f-c55ee7176d83', (SELECT type_id FROM machine_type WHERE type_name = 'Cuerda de Batalla')),
(uuid_generate_v4(), TRUE, 'Disponible', '004146d3-9f13-4eab-982f-c55ee7176d83', (SELECT type_id FROM machine_type WHERE type_name = 'Máquina de extensión de pierna')),
(uuid_generate_v4(), TRUE, 'Disponible', '004146d3-9f13-4eab-982f-c55ee7176d83', (SELECT type_id FROM machine_type WHERE type_name = 'Máquina de extensión de pierna')),
(uuid_generate_v4(), TRUE, 'Disponible', '004146d3-9f13-4eab-982f-c55ee7176d83', (SELECT type_id FROM machine_type WHERE type_name = 'TRX')),
(uuid_generate_v4(), TRUE, 'Disponible', '004146d3-9f13-4eab-982f-c55ee7176d83', (SELECT type_id FROM machine_type WHERE type_name = 'Máquina de curl de pierna')),
(uuid_generate_v4(), TRUE, 'Disponible', '004146d3-9f13-4eab-982f-c55ee7176d83', (SELECT type_id FROM machine_type WHERE type_name = 'Máquina de curl de pierna')),
(uuid_generate_v4(), TRUE, 'Disponible', '004146d3-9f13-4eab-982f-c55ee7176d83', (SELECT type_id FROM machine_type WHERE type_name = 'Balón Medicinal')),
(uuid_generate_v4(), TRUE, 'Disponible', '004146d3-9f13-4eab-982f-c55ee7176d83', (SELECT type_id FROM machine_type WHERE type_name = 'Máquina de abductores de hack squal')),
(uuid_generate_v4(), TRUE, 'Disponible', '004146d3-9f13-4eab-982f-c55ee7176d83', (SELECT type_id FROM machine_type WHERE type_name = 'Máquina de abductores de hack squal')),
(uuid_generate_v4(), TRUE, 'Disponible', '004146d3-9f13-4eab-982f-c55ee7176d83', (SELECT type_id FROM machine_type WHERE type_name = 'Press de hombros con martillo')),
(uuid_generate_v4(), TRUE, 'Disponible', '004146d3-9f13-4eab-982f-c55ee7176d83', (SELECT type_id FROM machine_type WHERE type_name = 'Press de hombros con martillo')),
(uuid_generate_v4(), TRUE, 'Disponible', '004146d3-9f13-4eab-982f-c55ee7176d83', (SELECT type_id FROM machine_type WHERE type_name = 'Máquina de Gemelos')),
(uuid_generate_v4(), TRUE, 'Disponible', '004146d3-9f13-4eab-982f-c55ee7176d83', (SELECT type_id FROM machine_type WHERE type_name = 'Elevaciones laterales')),
(uuid_generate_v4(), TRUE, 'Disponible', '004146d3-9f13-4eab-982f-c55ee7176d83', (SELECT type_id FROM machine_type WHERE type_name = 'Elevaciones laterales')),
(uuid_generate_v4(), TRUE, 'Disponible', '004146d3-9f13-4eab-982f-c55ee7176d83', (SELECT type_id FROM machine_type WHERE type_name = 'Máquina de Bíceps')),
(uuid_generate_v4(), TRUE, 'Disponible', '004146d3-9f13-4eab-982f-c55ee7176d83', (SELECT type_id FROM machine_type WHERE type_name = 'Máquina de Bíceps')),
(uuid_generate_v4(), TRUE, 'Disponible', '004146d3-9f13-4eab-982f-c55ee7176d83', (SELECT type_id FROM machine_type WHERE type_name = 'Prensa de Tríceps con Barra')),
(uuid_generate_v4(), TRUE, 'Disponible', '004146d3-9f13-4eab-982f-c55ee7176d83', (SELECT type_id FROM machine_type WHERE type_name = 'Prensa de Tríceps con Barra')),
(uuid_generate_v4(), TRUE, 'Disponible', '004146d3-9f13-4eab-982f-c55ee7176d83', (SELECT type_id FROM machine_type WHERE type_name = 'Máquina de Abdominales')),
(uuid_generate_v4(), TRUE, 'Disponible', '004146d3-9f13-4eab-982f-c55ee7176d83', (SELECT type_id FROM machine_type WHERE type_name = 'Máquina de Abdominales')),
(uuid_generate_v4(), TRUE, 'Disponible', '004146d3-9f13-4eab-982f-c55ee7176d83', (SELECT type_id FROM machine_type WHERE type_name = 'Banco Abdominal')),
(uuid_generate_v4(), TRUE, 'Disponible', '004146d3-9f13-4eab-982f-c55ee7176d83', (SELECT type_id FROM machine_type WHERE type_name = 'Banco Abdominal')),
(uuid_generate_v4(), TRUE, 'Disponible', '004146d3-9f13-4eab-982f-c55ee7176d83', (SELECT type_id FROM machine_type WHERE type_name = 'Banco Plano')),
(uuid_generate_v4(), TRUE, 'Disponible', '004146d3-9f13-4eab-982f-c55ee7176d83', (SELECT type_id FROM machine_type WHERE type_name = 'Banco Plano')),
(uuid_generate_v4(), TRUE, 'Disponible', '004146d3-9f13-4eab-982f-c55ee7176d83', (SELECT type_id FROM machine_type WHERE type_name = 'Rack de Pesas'));
