package frontend.admin.inventoryreports;

import backend.models.gym.Branch;
import backend.models.gym.Equipment;
import backend.services.BranchService;
import backend.services.EquipmentService;
import backend.util.ColorApp;
import com.formdev.flatlaf.FlatClientProperties;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableModel;

/**
 *
 * @author michael
 */
public class EquipmentBranchPanel extends javax.swing.JPanel {

    private final EquipmentService equipmentService = new EquipmentService();
    private final BranchService branchesService = new BranchService();

    /**
     * Creates new form EquipmentBranchPanel
     */
    public EquipmentBranchPanel() {
        initComponents();
        this.styleComponents();
        this.fillGymBranch();
        this.fillTable();
        this.moreInfo();
        gymBranchCombobox.addActionListener(e -> this.filterTableByBranch());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane1 = new javax.swing.JScrollPane();
        clientsTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        gymBranchCombobox = new javax.swing.JComboBox<>();
        updateTableBtn = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        clientsTable = new javax.swing.JTable(){
            public boolean isCellEditable(int row, int col) {
                return false;
            }
        };
        clientsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "NO.", "UUID", "Nombre", "Estado", "Ubicación", "Descripción"
            }
        ));
        jScrollPane1.setViewportView(clientsTable);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 889;
        gridBagConstraints.ipady = 345;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(7, 6, 6, 6);
        add(jScrollPane1, gridBagConstraints);

        jLabel1.setText("Filtrar por:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 300, 0, 0);
        add(jLabel1, gridBagConstraints);

        gymBranchCombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 83;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 8, 10, 0);
        add(gymBranchCombobox, gridBagConstraints);

        updateTableBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/updateList.png"))); // NOI18N
        updateTableBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateTableBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 12;
        gridBagConstraints.ipady = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 40, 5, 10);
        add(updateTableBtn, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void updateTableBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateTableBtnActionPerformed
        this.fillTable();
        this.styleComponents();
        this.gymBranchCombobox.setSelectedIndex(0);
    }//GEN-LAST:event_updateTableBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable clientsTable;
    private javax.swing.JComboBox<String> gymBranchCombobox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton updateTableBtn;
    // End of variables declaration//GEN-END:variables

    /**
     * Da estilo a los componentes de esta clase.
     */
    private void styleComponents() {
        jLabel1.putClientProperty("FlatLaf.style", "font: bold +14; foreground: " + ColorApp.GREEN + ";");

        gymBranchCombobox.putClientProperty("FlatLaf.style",
                "arc: 15;"
                + "font: 14;"
                + "foreground: " + ColorApp.GREEN_DARK + ";");
        gymBranchCombobox.setPreferredSize(new Dimension(150, 30));

        updateTableBtn.putClientProperty(FlatClientProperties.BUTTON_TYPE, "roundRect");
        updateTableBtn.putClientProperty(FlatClientProperties.STYLE,
                "arc: 15;"
                + "font: bold +12;"
                + "background: " + ColorApp.GREEN + ";"
                + "foreground: " + ColorApp.WHITE + ";"
                + "hoverBackground: " + ColorApp.GREEN_DARK + ";"
                + "pressedBackground: " + ColorApp.GREEN_DARKED + ";");
        updateTableBtn.setHorizontalTextPosition(SwingConstants.CENTER);
        updateTableBtn.setVerticalTextPosition(SwingConstants.BOTTOM);
        updateTableBtn.setToolTipText("Actualizar listado");

        clientsTable.setRowHeight(30);
        clientsTable.setGridColor(Color.GREEN);
        clientsTable.setShowGrid(true);
        clientsTable.setFillsViewportHeight(true);
        clientsTable.setAutoCreateRowSorter(true);
        clientsTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        clientsTable.getColumnModel().getColumn(4).setPreferredWidth(200);
        clientsTable.getColumnModel().getColumn(4).setMaxWidth(300);
        clientsTable.getColumnModel().getColumn(4).setMinWidth(150);

        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(SwingConstants.CENTER);
        for (int i = 0; i < clientsTable.getColumnCount(); i++) {
            clientsTable.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
        }

        clientsTable.getTableHeader().setDefaultRenderer(new DefaultTableCellRenderer() {
            @Override
            public java.awt.Component getTableCellRendererComponent(javax.swing.JTable table, Object value,
                    boolean isSelected, boolean hasFocus, int row, int column) {
                super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
                setHorizontalAlignment(SwingConstants.CENTER);
                setBackground(Color.decode(ColorApp.GREEN.toString()));
                setForeground(Color.WHITE);
                setFont(getFont().deriveFont(java.awt.Font.BOLD, 14f));
                return this;
            }
        });

        for (int column = 0; column < clientsTable.getColumnCount(); column++) {
            int maxWidth;
            if (column == 0) {
                maxWidth = 40;
            } else if (column == 7) {
                maxWidth = 120;
            } else {
                maxWidth = 70;
            }

            for (int row = 0; row < clientsTable.getRowCount(); row++) {
                TableCellRenderer renderer = clientsTable.getCellRenderer(row, column);
                java.awt.Component comp = clientsTable.prepareRenderer(renderer, row, column);
                maxWidth = Math.max(comp.getPreferredSize().width + 10, maxWidth);
            }
            clientsTable.getColumnModel().getColumn(column).setPreferredWidth(maxWidth);
        }
    }

    /**
     * Llena la tabla con los datos de la base de datos.
     */
    private void fillTable() {
        String[] columns = {"No.", "UUID", "Nombre", "Estado", "Descripción", "Ubicación"};
        ArrayList<Equipment> equipments = this.equipmentService.getEquipments();
        DefaultTableModel model = new DefaultTableModel(columns, equipments.size());
        clientsTable.setModel(model);

        TableModel dataModel = clientsTable.getModel();

        for (int i = 0; i < equipments.size(); i++) {
            Equipment equipment = equipments.get(i);
            String stateEquipment = equipment.isState() ? "Disponible" : "No disponible";

            if (equipment.isState()) {
                dataModel.setValueAt((i + 1), i, 0);
                dataModel.setValueAt(equipment.getId().toString(), i, 1);
                dataModel.setValueAt(equipment.getName(), i, 2);
                dataModel.setValueAt(stateEquipment, i, 3);
                dataModel.setValueAt(equipment.getDescription(), i, 4);
                dataModel.setValueAt(equipment.getLocation(), i, 5);
            }

        }
        this.styleComponents();
    }

    /**
     * Sirve para llenar el JComboBox con las sucursales existentes.
     */
    private void fillGymBranch() {
        gymBranchCombobox.removeAllItems();
        ArrayList<Branch> branches = branchesService.getBranches();

        gymBranchCombobox.addItem("Todas las sucursales");

        if (!branches.isEmpty()) {
            for (Branch branch : branches) {
                gymBranchCombobox.addItem(branch.getName());
            }
        }
    }

    /**
     * Filtra la tabla según la sucursal seleccionada en el JComboBox.
     */
    private void filterTableByBranch() {
        String selectedBranch = (String) gymBranchCombobox.getSelectedItem();
        ArrayList<Equipment> equipments = equipmentService.getEquipments();

        if (selectedBranch != null && selectedBranch.equals("Todas las sucursales")) {
            fillTable();
            return;
        }

        ArrayList<Equipment> filtered = new ArrayList<>();
        for (Equipment eq : equipments) {
            if (eq.getLocation().equals(selectedBranch)) {
                filtered.add(eq);
            }
        }

        String[] columns = {"No.", "UUID", "Nombre", "Estado", "Descripción", "Ubicación"};
        DefaultTableModel model = new DefaultTableModel(columns, filtered.size());
        clientsTable.setModel(model);

        TableModel dataModel = clientsTable.getModel();
        for (int i = 0; i < filtered.size(); i++) {
            Equipment equipment = filtered.get(i);
            String stateEquipment = equipment.isState() ? "Disponible" : "No disponible";

            dataModel.setValueAt((i + 1), i, 0);
            dataModel.setValueAt(equipment.getId().toString(), i, 1);
            dataModel.setValueAt(equipment.getName(), i, 2);
            dataModel.setValueAt(stateEquipment, i, 3);
            dataModel.setValueAt(equipment.getDescription(), i, 4);
            dataModel.setValueAt(equipment.getLocation(), i, 5);
        }

        this.styleComponents();
    }

    /**
     * Muestra un tipo pop up mostrando la descripción de una casilla
     * seleccionada de un equipo.
     */
    private void moreInfo() {
        clientsTable.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            @Override
            public void mouseMoved(MouseEvent e) {
                int row = clientsTable.rowAtPoint(e.getPoint());
                int col = clientsTable.columnAtPoint(e.getPoint());
                if (row > -1 && col > -1) {
                    clientsTable.setToolTipText("Doble click para más información");
                } else {
                    clientsTable.setToolTipText(null);
                }
            }
        });

        clientsTable.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                if (e.getClickCount() == 2) {
                    int row = clientsTable.rowAtPoint(e.getPoint());
                    int col = clientsTable.columnAtPoint(e.getPoint());

                    if (row > -1 && col > -1) {
                        Object value = clientsTable.getValueAt(row, col);
                        if (value != null) {
                            JOptionPane.showMessageDialog(
                                    null,
                                    value.toString(),
                                    "Detalles",
                                    javax.swing.JOptionPane.INFORMATION_MESSAGE
                            );
                        }
                    }
                }
            }
        });
    }
}
